[commands.kit]
info = "Currently selected kit: <pri><kit_id>"
save.confirm = "Your inventory will now be saved! <bold>Current inventory layouts of players are going to be lost!/<bold><br>[<bold><confirm></bold>]"
save = "The kit inventory has been updated."

unselected = "You do not have a kit selected. <click:suggest_command:'/kit select '>/kit select <tag>"

rename = "<bold><pri>RENAMED!<reset> Your <pri>selected kit's</pri> (<kit_id>) display name to <sec><name><reset>"
icon = "<bold><pri>NICE ICON!<reset> Changed icon of your <pri>current kit</pri> to <sec><icon><reset>."
icon.empty = "The kit icon cannot be air."
give = "The inventory has been loaded."
create = "<bold><sec>CREATED!<reset> The kit and selected it (<pri><id><reset>)"
select = "<bold><#d49de0>SELECTED!<reset> <pri><name><reset>"
select.unknown = "<bold><red>UNKNOWN!</reset> <pri><name><reset>"
reset.error = "Could not reset the kit, an error occured."
reset = "<bold><#ff0000>RESET!<reset>"
list = "Global Kits: <list>"

global.already = "The kit is already global."
global.exists = "Ein Global Kit mit dem Namen <pri><name> <reset>existiert schon."
global.set = "Das Kit wurde globalisiert."
global.unknown = "Ein Global Kit mit dem Namen <pri><name> <reset>existiert nicht."
global.unset = "<bold><#6c9ef5>UNSET!<reset> The kit is no longer global and now owned by you on id <pri><id><reset>."
global.disallowedCharacter = "<bold><red>DISALLOWED!<reset> The global kit name contains disallowed characters (marked red): <characters>"

[arena]
disabled = "<red>Serverwide disabled"
autosave = "<bold><color:#88ff88>SAVED!<reset> The world has been auto-saved."
save = "<bold><color:#88ff88>SAVED!<reset> <pri><username><reset> saved the current world. That makes them a hero!"

[commands.arena]
create = "Die Arena <pri><key><reset> wird erstellt. Sobald diese bereit ist wirst du automatisch dorthin teleportiert."
create.alreadyExists = "An arena with the same name already exists. Would you like to teleport to it? <pri><bold><click:run_command:'/arena goto %s'>Yes"
create.namespace.minecraft = "You cannot create an arena without any <bold><pri>:</pri></bold> or with them </pri>minecraft</pri> namespace."
create.namespace.length = "The key cannot be longer than 255 characters."

not_arena = "<bold><red>WHAT?!<reset> The world, you are currently in, isn't an arena."

rename = "<bold><pri>RENAMED!<reset> Your <pri>current arena's</pri> display name to <sec><name><reset>."
icon = "<bold><pri>NICE ICON!<reset> Changed icon of your <pri>current arena</pri> to <sec><icon><reset>."

goto = "Teleported to arena <key>"

enable = "<bold><color:#ff8888>ENABLED!<reset> Published arena <pri><key><reset> to be played."
disable = "<bold><color:#ff8888>DISABLED!<reset> Published arena <pri><key><reset> from being played."

list.namespace = "Listing all arenas of namespace <namespace>: <br><arenas>"
list.all = "Listing all arenas: <br><arenas>"
list.none = "There are no arenas available to show."

export.complete = "The current arena <sec><arena></sec> has been successfully uploaded to <pri><url></pri>."
export.failed = "Failed to export the current arena: <error>"

publish.save = "Publishing started, please stay still."
publish.unfinished = "Publication failed, you do not have set all parameters for the arena (missing <missing_count>)"
publish.success = "Publication for arena <pri><display_name><reset> finished successfully"

import = "<bold><color:#3061e8>IMPORTED!<reset> <arena><reset> successfully."
import.anvil.big = "<bold><red>HUGE!<reset> The world you are trying to import is <italic>too</italic> big."
import.anvil.invalid = "<bold><red>INVALID!<reset> The anvil world is invalid: <message>"

[gui.arena.settings]
title = "Arena Settings"
name.input = "Please enter the new arena name in chat:"

set.position = "Position was set to <pos><reset>."

[gui.arena.publication]
title = "Publish Arena"
confirm = "<green><bold>Confirm Publication"

[gui.arena.worlds]
create = "<click:suggest_command:'/arena create '><bold><sec>Click here</sec></bold> to create a new arena"

[gui.selectItem]
title = "Select an item from your inventory"
cancel = "<red>Cancel"
set = "<green>Set Item"
item = "<sec>Selected Item"