untranslated = "<text>"

# Languages
language.change = """
  Your language is now English (United States.)
  <br>Help us translate the network into your language on <click:open_url:'https://dc.kitpvp.world'><color:#5865f2>our Discord</color></click>.
"""

[core.event.rank.update]
rankedUnblock = """
    You have been unblocked from the ranked queue.
"""
utility = """
    You received a special rank: <pri><rank><reset>
    <br><sec>Thank you</sec> for your support.
"""
team = """
    You have received a team rank: <pri><rank><reset>
    <br><sec>Thank you</sec> for your support.
"""
sponsor = """
    Thank you for your purchase on <pri>kitpvp.world</pri>.
    You have received the <sec><rank><reset> rank.
 """

[gui.languages]
title = "Change language"
untranslated.name = "<gray>Didn't find your language?"
untranslated.lore = """
  <green>Help us<gray>, translate the network"
  <br><gray>into your language.
"""
untranslated.book = """
    <black><bold>Thank you</bold> for trying to improve KitPvP.world!
    <br>For translating KitPvP.world into more languages, you'll receive <bold>unique rewards</bold>.
    <br>Please <bold>open a ticket</bold> on our discord server:
    <br><click:open_url:'https://dc.kitpvp.world'>                                       <br>
    <dark_gray>[<color:#5865f2><bold>Join our Discord</bold></color>]                        <br>
"""

[gui.kitView]
title = "View Kit"

# Common
[gui.common]
error.clickitem = "An unexpected error occurred trying to click that item"

# Generic Things
[generic]
back = "Back"
error.clickitem = "An error occurred. Try again or contact support."
error = "An error occurred."
error.target.offline = "This player is not online."
error.target.unknown = "This player is unknown."
error.rank.unknown = "This rank does not exist."
error.kit.unknown = "Kit was not found."

next = "Next Page"
previous = "Previous Page"

[time]
seconds = "%s seconds"
minutes = "%s minutes"
hours = "%s hours"
days = "%s days"
months = "%s months"

[time.relative]
seconds = "%s seconds ago"
minutes = "%s minutes ago"
hours = "%s hours ago"
days = "%s days ago"
months = "%s months ago"

# Chat
[chat]
message.tooSimilar = "This message is too similar to your last one."
message.spam = "You are sending messages too quickly."

# Games
[games.phase.counter]
starting.secondsFormat = "The game starts in <pri><seconds_left>s<reset>."
stopping.secondsFormat = "The game stops in <pri><seconds_left>s<reset>."

# Commands

[commands]
coins.self.singular = "You currently have <gold>one Coin<reset>."
coins.self.plural = "You currently have <gold><coins> Coins<reset>."

coins.other.singular = "<pri><target><reset> currently has <gold>one Coin"
coins.other.plural = "<pri><target><reset> currently has <gold><coins> Coins"

xp.self = "You have <pri><xp><reset> XP and are therefore level <level><reset> <dark_gray>[<progress><reset><dark_gray>]"
xp.other = "<target><reset> has <pri><xp><reset> XP and is therefore level <level><reset> <dark_gray>[<progress><reset><dark_gray>]"

xp = """
  <br><yellow>Level statistics of <gold><bold><name><reset>
  <br>Rank: <rank><reset>
  <br>Level: <level><reset>
  <br>Collected XP: <xp><reset>/<yellow><xp_needed><reset>
  <br><dark_gray>| » <xp_bar><reset>
  <br>Collected Achievements: <pri><achievements><reset>/<sec><total_achievements><reset>
"""

rank.singular = "Your rank <rank><reset> is active for 1 day."
rank.plural = "Your rank <rank><reset> is active for <days> days."
rank.infinite = "Your rank <rank><reset> does not have a limit."
rank.none = "You don't own any rank."

stats = """
    <br><yellow>Duels statistics of <gold><bold><rank><reset> <name></bold></gold> (<range>)<reset>
    <br><hover:show_text:'Click to view profile'><click:run_command:'/profile %1$s'>[<gold><bold>View Profile</bold></gold>]<reset>
    <br>Global Rank: <global_rank><reset>
    <br>Global Elo: <global_elo><reset>
    <br>K/D: <gray><kills_deaths><reset>
    <br>Games played: <gray><games_played><reset>
    <br>Highest Winstreak: <top_winstreak><reset>
    <br><hover:show_text:'Click to view more'><click:run_command:'/level %1$s'>Level: <level> <reset>
"""
stats.currentSeason = "Seasonal"
stats.alltime = "Alltime"

ping.self = "Ping: <pri><ping>"
ping.other = "The Ping of the player <sec><target><reset> is: <pri><ping>"

language.unknown = "Language not found. <pri>Help us<reset> translate the network into your language on <click:open_url:'https://dc.kitpvp.world'><color:#5865f2>our Discord</color>."

lobby.alreadyConnected = "You are already connected to a lobby server."

[commands.ranks]
add = "Added the rank of <pri><target><reset> to <sec><rank><reset."
remove = "Added the rank of <pri><target><reset> to <sec><rank><reset."
add = "Added the rank of <pri><target><reset> to <sec><rank><reset."

reload = "<green>Reloaded."

[commands.test]
coins.set = "Your coins have been set to <gold><coins><reset>."
coins.remove = "You now have <gold><coins><reset> coins."
coins.remove.missing = "You are missing <gold><coins><reset> coins."
coins = "You have <gold><coins>"

xp.add = "Your XP has been increased by <pri><xp><reset> XP."
xp.set = "Your XP has been set to <pri><xp>reset>."
xp.reset = "Your XP has been reset."
xp = "You have <pri><xp><reset> XP."

nick.nick = "You now nicked as <pri><name><reset>."
nick.nicked = "You already nicked."
nick.unnick = "You are unnicked now."
nick.unnicked = "You are not nicked"

uuid = "Your UUID is: <hover:show_text:'Click to copy'><click:copy_to_clipboard:%1$s>%1$s</click></hover>"

[commands.service]
maintenance.allow = "You <sec>allowed</sec> the user <target><reset> to join while in maintenance mode."
maintenace.allow.already = "The user <target><reset> is already on the allowlist."
maintenance.disallow = "You <red>removed</red> the user <target><reset> from the maintenace allowlist."
maintenace.disallow.already = "The user <target><reset> not added to the allowlist."
maintenance.list = """
Showing the status of the maintenance:
<br> ● Maintenance Status: <status><reset>
<br> ● Maintenance Allowed Users: <list>
"""

[commands]
help = """
  <gold>Informationen about commands
  <br>
  <br><click:suggest_command:'/l '><yellow>/l</click> <dark_gray>- <reset>Brings you back to the Lobby
  <br><click:suggest_command:'/hub '><yellow>/hub</click> <dark_gray>- <reset>Brings you back to the Lobby
  <br><click:suggest_command:'/duel '><yellow>/duel</yellow> [<yellow>name</yellow>]</click> <dark_gray>- <reset>Duels the player
  <br><click:suggest_command:'/profile '><yellow>/profile</click> <dark_gray>- <reset>Shows the ranked stats
  <br><click:suggest_command:'/stats '><yellow>/stats</click> <dark_gray>- <reset>Shows an overview for your stats
  <br><click:suggest_command:'/coins '><yellow>/coins</click> <dark_gray>-</dark_gray> <reset>Shows your coins
  <br><click:suggest_command:'/friends'><yellow>/friends</click> <dark_gray>- <reset>Opens friends
  <br><click:suggest_command:'/friend add '>/<yellow>friend add</click> <dark_gray>- <reset>Adds someone as a friend
"""

[moderation]
warned = "<pri><target><reset> was warnt for <sec><reason><reset> and is now for <red><days_banned><reset> days banned."
report = "You reported the player <pri><target><reset> for <sec><reason>."
error.chat.block = "I know you are mad, but please be <bold>respectful</bold>."
error.chat.mute = "You were banned from the chat for <red><duration><reset> because of misbehavior: <br><reason>"

[moderation.report.reason]
cheating = "Cheating"
chat = "Chat Nachricht(en)"
kiting = "Kiting"
skin = "Skin"
name = "Benutzername"
clan = "Clan-Name"
status = "Freundesstatus"
hunting = "Hunting"
teaming = "Teaming"
boosting = "Boosting"
trolling = "Trolling"

[moderation.admin]
profile.loading = "Loading Profile of <target><reset>..."
profile = """
  Moderation profile of <pri><target><reset> (<rank><reset>)<br>
  User Id: <user_id><br>
  <br>
  Status: <status><reset><br>
  Last Online: <last_online><reset><br>
  Duration of the session: <session_time><reset><br>
  <br>
  Client Brand: <brand><reset><br>
  IP: <ip><reset><br>
  ISP (Host Name): <host_name><reset><br>
  <br>
  NameMC Profile: <namemc><reset><br>
  Crafty Profile: <crafty><reset><br>
  Laby Profile: <laby><reset><br>
  Direcly Suspicious Alts: <hover:show_text:'<yellow>Show Tree'><alts><reset><br>
  <br>
  Profile loading time: <loading_time>ms<reset>
"""

admin.alts = """
  Suspicious accounts of <pri><target><reset> (<rank><reset>)<br>
  <br>
  <alts><br>
  <own_profile><reset> (Own profile) 
  <br>
  Alts loading Time: <loading_time>ms<reset>
"""

[gui]

[tablist]
header = "<aqua>You are playing on <yellow><bold>KITPVP.WORLD"
footer = "<green>ѕᴜᴘᴘᴏʀᴛ ᴜѕ ᴏɴ <red><bold>STORE.KITPVP.WORLD"
