untranslated = "<text>"

# Languages
language.change = """
  Your language is now English (United States.)
  <br>Help us translate the network into your language on <click:open_url:'https://dc.kitpvp.world'><color:#5865f2>our Discord</color></click>.
"""

[gui.languages]
title = "Change language"
untranslated.name = "<gray>Didn't find your language?"
untranslated.lore = """
  <green>Help us<gray>, translate the network"
  <br><gray>into your language.
"""
untranslated.book = "<br><br><br><br><br><br><br><br><br><br><br><br><green><bold><click:open_url:'https://dc.kitpvp.world'>Help here!<reset>"

# Common
[gui.common]
error.clickitem = "An unexpected error occurred trying to click that item"

# Generic Things
[generic]
error.clickitem = "An error occurred. Try again or contact support."
error = "An error occurred."
error.target.offline = "This player is not online."
error.target.unknown = "This player is unknown."
error.rank.unknown = "This rank does not exist."
error.kit.unknown = "Kit was not found."

next = "Next Page"
previous = "Previous Page"


[time.relative]
seconds = "%s seconds ago"
minutes = "%s minutes ago"
hours = "%s hours ago"
days = "%s days ago"
months = "%s months ago"

# Chat
[chat]
message.tooSimilar = "This message is too similar to your last one."
message.spam = "You are sending messages too quickly."

# Games
[games.phase.counter]
starting.secondsFormat = "The game starts in <pri><seconds_left>s<reset>."
stopping.secondsFormat = "The game stops in <pri><seconds_left>s<reset>."

# Commands

[commands]
coins.self.singular = "You currently have <gold>one Coin<reset>."
coins.self.plural = "You currently have <gold><coins> Coins<reset>."

coins.other.singular = "<pri><target><reset> currently has <gold>one Coin"
coins.other.plural = "<pri><target><reset> currently has <gold><coins> Coins"

xp.self = "You have <pri><xp><reset> XP and are therefore level <level><reset> <dark_gray>[<progress><reset><dark_gray>]"
xp.other = "<target><reset> has <pri><xp><reset> XP and is therefore level <level><reset> <dark_gray>[<progress><reset><dark_gray>]"

xp = """
  <br><yellow>Level statistics of <gold><bold><name><reset>
  <br>Rank: <rank><reset>
  <br>Level: <level><reset>
  <br>Collected XP: <xp><reset>/<yellow><xp_needed><reset>
  <br><dark_gray>| » <xp_bar><reset>
  <br>Collected Achievements: <pri><achievements><reset>/<sec><total_achievements><reset>
"""

ping.self = "Ping: <pri><ping>"
ping.other = "The Ping of the player <sec><target><reset> is: <pri><ping>"

language.unknown = "Language not found. <pri>Help us<reset> translate the network into your language on <click:open_url:'https://dc.kitpvp.world'><color:#5865f2>our Discord</color>."

[commands.ranks]
set = "Changed the rank of <pri><target><reset> to <sec><rank><reset."
reload = "<green>Reloaded."

[commands.test]
coins.set = "Your coins have been set to <gold><coins><reset>."
coins.remove = "You now have <gold><coins><reset> coins."
coins.remove.missing = "You are missing <gold><coins><reset> coins."
coins = "You have <gold><coins>"

xp.add = "Your XP has been increased by <pri><xp><reset> XP."
xp.set = "Your XP has been set to <pri><xp>reset>."
xp.reset = "Your XP has been reset."
xp = "You have <pri><xp><reset> XP."

nick.nick = "You now nicked as <pri><name><reset>."
nick.nicked = "You already nicked."
nick.unnick = "You are unnicked now."
nick.unnicked = "You are not nicked"

uuid = "Your UUID is: <hover:show_text:'Rechtsklick zum kopieren'><click:copy_to_clipboard:%1$s>%1$s</click></hover>"

[commands]
help = """
  <gold>Informationen about commands
  <br>
  <br><click:suggest_command:'/l '><yellow>/l</click> <dark_gray>- <reset>Brings you back to the Lobby
  <br><click:suggest_command:'/hub '><yellow>/hub</click> <dark_gray>- <reset>Brings you back to the Lobby
  <br><click:suggest_command:'/duel '><yellow>/duel</yellow> [<yellow>name</yellow>]</click> <dark_gray>- <reset>Duels the player
  <br><click:suggest_command:'/profile '><yellow>/profile</click> <dark_gray>- <reset>Shows the ranked stats
  <br><click:suggest_command:'/coins '><yellow>/coins</click> <dark_gray>-</dark_gray> <reset>Shows your coins
  <br><click:suggest_command:'/friends'><yellow>/friends</click> <dark_gray>- <reset>Opens friends
  <br><click:suggest_command:'/friend add '>/<yellow>friend add</click> <dark_gray>- <reset>Adds someone as a friend
"""

[moderation]
warned = "<pri><target><reset> was warnt for <sec><reason><reset> and is now for <red><days_banned><reset> days banned."
report = "You reported the player <pri><target><reset> for <sec><reason>."
error.chat.block = "I know you are mad, but please be <bold>respectful</bold>."
error.chat.mute = "You were banned from the chat for <red><duration><reset> because of misbehavior: <br><reason>"

admin.profile.loading = "Loading Profile of <target><reset>..."
admin.profile = """
  Moderation profile from <pri><target><reset> (<rank><reset>)<br>
  <br>
  Status: <status><reset><br>
  Last Online: <last_online><reset><br>
  Duration of the session: <session_time><reset><br>
  <br>
  Client Brand: <brand><reset><br>
  IP: <ip><reset><br>
  ISP (Host Name): <host_name><reset><br>
  <br>
  NameMC Profile: <namemc><reset><br>
  Crafty Profile: <crafty><reset><br>
  Laby Profile: <laby><reset><br>
  Suspicious Alts: <hover:show_text:'<yellow>Anzeigen'><alts><reset><br>
  <br>
  Profile loading time: <loading_time>ms<reset>
"""

admin.alts = """
  Suspicious accounts from <pri><target><reset> (<rank><reset>)<br>
  <br>
  <alts><br>
  <own_profile><reset> (Own profile) 
  <br>
  Alts loading Time: <loading_time>ms<reset>
"""


[moderation.report.reason]
cheating = "Cheating"
chat = "Chat Nachricht(en)"
kiting = "Kiting"
skin = "Skin"
name = "Benutzername"
clan = "Clan-Name"
status = "Freundesstatus"
hunting = "Hunting"
teaming = "Teaming"
boosting = "Boosting"
trolling = "Trolling"

[gui]
