untranslated = "<text>"

# Languages
language.change = """
  Your language is now English (United States.)
  <br>Help us translate the network into your language on <click:open_url:'https://discord.gg/JEYwEcRHnw'><color:#5865f2>our Discord</color></click>.
"""
resourcePack.requirement = """
<st><gradient:#F48C04:#FFE22C:-0.5>                               </gradient></st><br>
<#FFE22C>Hey there, Warrior!<br>
<br>
<#A5ACB8>In order to play<br>
 on the KitPvP.world<br>
You need to accept our<br>
resource pack.<br>
<br>
<st><gradient:#F48C04:#FFE22C:-0.5>                               </gradient></st>
"""

[core.event.rank.update]
rankedUnblock = """
    You have been unblocked from the ranked queue.
"""
utility = """
    You received a special rank: <pri><rank><reset>
    <br><sec>Thank you</sec> for your support.
"""
team = """
    You have received a team rank: <pri><rank><reset>
    <br><sec>Thank you</sec> for your support.
"""
sponsor = """
    Thank you for your purchase on <pri>KitPvP.world</pri>.<br>
    You have received the <sec><rank><reset> rank.
 """

[gui.languages]
title = "Change language"
untranslated.name = "<gray>Didn't find your language?"
untranslated.lore = """
  <green>Help us<gray>, translate the network
  <br><gray>into your language.
"""
untranslated.book = """
    <black><bold>Thank you</bold> for trying to improve KitPvP.world!
    <br>For translating KitPvP.world into more languages, you'll receive <bold>unique rewards</bold>.
    <br>Please <bold>open a ticket</bold> on our discord server:
    <br><click:open_url:'https://discord.gg/JEYwEcRHnw'>                                       <br>
    <dark_gray>[<color:#5865f2><bold>Join our Discord</bold></color>]                        <br>
"""

[gui.kitView]
title = "View Kit"

[gui.core.buy]
title = "<gray>Buy<dark_gray>: <item>"
remainingCoins = "<sec>Coins afterward<dark_gray>: "
missingCoins = "Coins missing:"
purchased = "You have <sec>purchased</sec> the item <item><reset> for <yellow><coins><reset>, and have <gold><coins_remaining><reset> coins remaining."
error.missingCoins = "You cannot afford the item <item><reset>. You are missing <gold><coins><reset> coins."
error = "Failed to complete purchase of the item <item><reset>. Please, report this to our support. <dark_gray>[<yellow><clock><dark_gray>]"

# Generic Things
[generic]
back = "<red>Back"
error.clickitem = "An error occurred. Try again or contact support."
error = "An error occurred."
error.target.offline = "This player is not online."
error.target.unknown = "This player is unknown."
error.rank.unknown = "This rank does not exist."
error.kit.unknown = "Kit was not found."
error.arena.unknown = "Arena <arena><reset> was not found."
error.command = "Command execution of '<command>' failed unexpectedly. Please, report this issue to our support.<admin>"

next = "Next Page"
previous = "Previous Page"

[time]
now = "Now"
seconds = "%s seconds"
minutes = "%s minutes"
hours = "%s hours"
days = "%s days"
months = "%s months"

[time.relative]
now = "Now"
seconds = "%s seconds ago"
minutes = "%s minutes ago"
hours = "%s hours ago"
days = "%s days ago"
months = "%s months ago"

# Chat
[chat]
message.tooSimilar = "This message is too similar to your last one."
message.spam = "You are sending messages too quickly."

# Games
[games.phase.counter]
starting.secondsFormat = "The game starts in <pri><seconds_left>s<reset>."
stopping.secondsFormat = "The game stops in <pri><seconds_left>s<reset>."

# Commands

[commands]
coins.self = "You have <gold><coinsc:'0#no coins|1#one coin|1<%s coins'>."
coins.other = "<pri><target><reset> has <gold><coinsc:'0#no coins|1#one coin|1<%s coins'>."

xp.self = "You have <pri><xp><reset> XP and are therefore level <level><reset> <dark_gray>[<progress><reset><dark_gray>]"
xp.other = "<target><reset> has <pri><xp><reset> XP and is therefore level <level><reset> <dark_gray>[<progress><reset><dark_gray>]"

xp = """
  <br><yellow>Level statistics of <gold><bold><name><reset>
  <br>Rank: <rank><reset>
  <br>Level: <level><reset>
  <br>Collected XP: <xp><reset>/<yellow><xp_needed><reset>
  <br><dark_gray>| » <xp_bar><reset>
  <br>Collected Achievements: <pri><achievements><reset>/<sec><total_achievements><reset>
"""

stats = """
    <br><yellow>Duels statistics of <gold><bold><rank><reset> <name> (<range>)<reset>
    <br><hover:show_text:'Click to view profile'><click:run_command:'/profile %1$s'>[<gold><bold>View Profile</bold></gold>]<reset>
    <br>Global Rank: <global_rank><reset>
    <br>Global Elo: <global_elo><reset>
    <br>Kills: <yellow><kills><reset>
    <br>Deaths: <yellow><deaths><reset>
    <br>K/D: <yellow><kills_deaths><reset>
    <br>Games played: <yellow><games_played><reset>
    <br>Winstreak (Ranked): <yellow><winstreak_ranked> (Current)/<top_winstreak_ranked> (Highest)<reset>
    <br>Winrate (Ranked): <yellow><winrate_ranked><reset>
    <br>Winstreak (Unranked): <yellow><winstreak_unranked> (Current)/<top_winstreak_unranked> (Highest)<reset>
    <br>Winrate (Unranked): <yellow><winrate_unranked><reset>
    <br>Coins: <dark_gray>[</dark_gray><gold><coins></gold><dark_gray>]</dark_gray> <gold><coins_booster>%% Booster<reset>
    <br><hover:show_text:'Click to view more'><click:run_command:'/level %1$s'>Level: <level><reset> <color:#00FF7F><level_booster>%% Booster<reset>
"""
stats.currentSeason = "Seasonal"
stats.alltime = "Alltime"

ping.self = "Ping: <pri><ping>"
ping.other = "The Ping of the player <sec><target><reset> is: <pri><ping>"

language.unknown = "Language not found. <pri>Help us<reset> translate the network into your language on <click:open_url:'https://discord.gg/JEYwEcRHnw'><color:#5865f2>our Discord</color>."

lobby.alreadyConnected = "You are already connected to a lobby server."

help = """
  <gold>Informationen about commands
  <br>
  <br><click:suggest_command:'/l '><yellow>/l</click> <dark_gray>- <reset>Brings you back to the Lobby
  <br><click:suggest_command:'/hub '><yellow>/hub</click> <dark_gray>- <reset>Brings you back to the Lobby
  <br><click:suggest_command:'/duel '><yellow>/duel</yellow> [<yellow>name</yellow>]</click> <dark_gray>- <reset>Duels the player
  <br><click:suggest_command:'/profile '><yellow>/profile</click> <dark_gray>- <reset>Shows the ranked stats
  <br><click:suggest_command:'/stats '><yellow>/stats</click> <dark_gray>- <reset>Shows an overview for your stats
  <br><click:suggest_command:'/coins '><yellow>/coins</click> <dark_gray>-</dark_gray> <reset>Shows your coins
  <br><click:suggest_command:'/friends'><yellow>/friends</click> <dark_gray>- <reset>Opens friends
  <br><click:suggest_command:'/friend add '>/<yellow>friend add</click> <dark_gray>- <reset>Adds someone as a friend
"""

[commands.rank]
add.infinite = "Added the rank <rank><reset> to <pri><target><reset> <sec>indefinetly</sec>."
add.limited = "Added the rank <rank><reset> to <pri><target><reset> to till <sec><duration><reset>."
remove = "Removed the rank <sec><rank><reset> of <pri><target><reset>."

duration = "Your rank <rank><reset> is active for <daysc:'0#less than a day|one day|1<%s days'>."
infinite = "Your rank <rank><reset> does not have a limit."
none = "You don't own any rank."

target.none = "<target><reset> does not own any ranks."
target.info = "<target><reset> owns following ranks: <br><ranks>"

reload = "<green>Reloaded."

[commands.test]
coins.set = "Your coins have been set to <gold><coins><reset>."
coins.remove = "You now have <gold><coins><reset> coins."
coins.remove.missing = "You are missing <gold><coins><reset> coins."
coins = "You have <gold><coins>"

xp.add = "Your XP has been increased by <pri><xp><reset> XP."
xp.set = "Your XP has been set to <pri><xp>reset>."
xp.reset = "Your XP has been reset."
xp = "You have <pri><xp><reset> XP."

nick.nick = "You now nicked as <pri><name><reset>."
nick.nicked = "You already nicked."
nick.unnick = "You are unnicked now."
nick.unnicked = "You are not nicked"

uuid = "Your UUID is: <hover:show_text:'Click to copy'><click:copy_to_clipboard:%1$s>%1$s</click></hover>"

[commands.service]
maintenace.state = "Set maintenace mode to: <state>"
maintenance.allow = "You <sec>allowed</sec> the user <target><reset> to join while in maintenance mode."
maintenance.allow.already = "The user <target><reset> is already on the allowlist."
maintenance.disallow = "You <red>removed</red> the user <target><reset> from the maintenace allowlist."
maintenance.disallow.already = "The user <target><reset> not added to the allowlist."
maintenance.list = """
Showing the status of the maintenance:
<br> ● Maintenance Status: <status><reset>
<br> ● Maintenance Allowed Users: <list>
"""
maintenance.message.set = "Set maintenace message to: <message>"
maintenance.message.unset = "Unset maintenace message"

[moderation]
warned = "<pri><target><reset> was warnt for <sec><reason><reset> and is now for <red><days_banned><reset> days banned."
report = "You reported the player <pri><target><reset> for <sec><reason>."
error.chat.block = "I know you are mad, but please be <bold>respectful</bold>."
error.chat.mute = "You were banned from the chat for <red><duration><reset> because of misbehavior: <br><reason>"
kick = "Kicked the user <target><reset>."
kick.reason = "Kicked the user <target><reset> with reason <reason><reset>."

[moderation.report.reason]
cheating = "Cheating"
chat = "Chat Nachricht(en)"
kiting = "Kiting"
skin = "Skin"
name = "Benutzername"
clan = "Clan-Name"
status = "Freundesstatus"
hunting = "Hunting"
teaming = "Teaming"
boosting = "Boosting"
trolling = "Trolling"

[moderation.admin]
profile.loading = "Loading Profile of <target><reset>..."
profile = """
  Moderation profile of <pri><target><reset> (<rank><reset>)<br>
  User Id: <user_id><br>
  <br>
  Status: <status><reset><br>
  Last Online: <last_online><reset><br>
  Duration of the session: <session_time><reset><br>
  <br>
  Client Brand: <brand><reset><br>
  IP: <ip><reset><br>
  ISP (Host Name): <host_name><reset><br>
  <br>
  NameMC Profile: <namemc><reset><br>
  Crafty Profile: <crafty><reset><br>
  Laby Profile: <laby><reset><br>
  Direcly Suspicious Alts: <hover:show_text:'<yellow>Show Tree'><alts><reset><br>
  <br>
  Profile loading time: <loading_time>ms<reset>
"""

alts = """
  Suspicious accounts of <pri><target><reset> (<rank><reset>)<br>
  <br>
  <alts><br>
  <own_profile><reset> (Own profile) 
  <br>
  Alts loading Time: <loading_time>ms<reset>
"""
compare = """
  Comparing accounts <aqua><target></aqua> and <red><compare_to></red><br>
  <br>
  Kills (Target/Other): <aqua><wins_self></aqua>/<red><wins_other></red><br>
  Ranked Kills (Target/Other): <aqua><ranked_wins_self></aqua>/<red><ranked_wins_other></red><br>
  <br>
  Compare Loading Time: <loading_time>ms
"""

[gui]
report.title = "Melden <name>"

[tablist]
header = "<aqua>You are playing on <yellow><bold>KITPVP.WORLD"
footer = "<green>ѕᴜᴘᴘᴏʀᴛ ᴜѕ ᴏɴ <red><bold>STORE.KITPVP.WORLD"

[booster.type]
coins = "<gold>Coins Booster</gold>"
xp = "<color:#00FF7F>XP Booster</color>"

[booster.unit]
coins = "<gold>Coins</gold>"
xp = "<color:#00FF7F>XP</color>"
