[gui.cosmetics]
armor.equip.all = "<red>Equip All"
armor.unequip.all = "<red>Unequip All"
armor.overview = "Armorset Overview"

cosmetics.remove = "Remove equipped cosmetic"

ranks = "Rank-Cosmetics"

[cosmetics.rarity]
common = "Common"
rare = "Rare"
epic = "Epic"
legendary = "Legendary"

[cosmetics.armor]
leather = "Leather Armor"
chain = "Chainmail Armor"
gold = "Golden Armor"
iron = "Iron Armor"
diamond = "Diamond Armor"
netherite = "Netherite Armor"

[cosmetics.pet]
wolf = "Dog"
cat = "Cat"
rabbit = "Bunny"
sheep = "Sheep"
cow = "Cow"
chicken = "Chicken"
slime = "Slime"
pig = "Pig"
turtle = "Turtle"
silverfish = "Silverfish"

[gui.boosters]
use = "Used <type><reset>, you will now gain <multiplier><reset> more <unit_type> for <duration><reset>."
use.active = "You already have an <type><reset> active."
use.fail = "Failed to use the booster. Is it already used?"