[gui.cosmetics]
armor.equip.all = "<red>Equip All"
armor.unequip.all = "<red>Unequip All"
armor.overview = "Armorset Overview"

cosmetics.remove = "Remove equipped cosmetic"

[cosmetics.category]
hats="<aqua>Hats"
pets="<blue>Pets"
ranks = "<gold>Rank-Cosmetics"
particles="<gold>Particle Overview"
trail_particles="Trails"
join_particles="Join Particle"
kill_particles="Kill Particle"
mystic_particles="Mysterious Particles"
gadgets="<dark_green>Gadgets"
armor="<yellow>Wardrobe"
effects="<white>Effects"
abilitities="<green>Abilities"
balloons="<light_purple>Balloons"

[cosmetics.rarity]
common = "Common"
rare = "Rare"
epic = "Epic"
legendary = "Legendary"
rank = "Rank"

[cosmetics.armor]
leather = "Leather Armorset"
chain = "Chainmail Armorset"
gold = "Golden Armorset"
iron = "Iron Armorset"
diamond = "Diamond Armorset"
netherite = "Netherite Armorset"
champ = "Champ Armorset"
grand_champ = "Grand Champ Armorset"
ultra = "Ultra Armorset"

[cosmetics.pet]
wolf = "Dog"
cat = "Cat"
rabbit = "Bunny"
sheep = "Sheep"
cow = "Cow"
chicken = "Chicken"
slime = "Slime"
pig = "Pig"
turtle = "Turtle"
silverfish = "Silverfish"

[gui.boosters]
use = "Used <type><reset>, you will now gain <multiplier><reset> more <unit_type> for <duration><reset>."
use.active = "You already have an <type><reset> active."
use.fail = "Failed to use the booster. Is it already used?"