[commands.cosmetics]
gift.unknown = "Unable to gift unknown cosmetic: <cosmetic>"
gift = "Gifted <pri><target><reset> the cosmetic <sec><cosmetic>"

[commands.boosters]
query.xp = "<#00FF7F>XP Boosters"
query.coins = "<gold>Coin Boosters"
query = """
<reset>Showing your <bold><query_title></bold><br>
<reset>Available boosters:<br>
<available_boosters><br>
<br>
<reset>Active boosters:<br>
<active_boosters><br>
<br>
<#00FA9A><reset><bold>»</bold> <sec>+<total_boost>%%</sec> when gaining
"""
query.noActive = "No boosters active."
query.noAvailable = "<click:open_url:'https://store.kitpvp.world'>You do not own any boosters.<br>Visit <pri><bold>store.kitpvp.world</bold></pri> to purchase more.</click>"
use.unavailable = "There are no more boosters available."
use.confirm = "<click:run_command:'%s'>Please confirm that you would like to use the booster <booster> [<sec><bold>ACTIVATE</sec>]</click>"

[gui.cosmetics]
title = "Cosmetics"
armor.equip.all = "<red>Equip All"
armor.unequip.all = "<red>Unequip All"
armor.overview = "Armorset Overview"

remove = "Remove equipped cosmetic"

purchase_lore = """
<gray>Buyable in the <gold>cosmetics store</gold><br>
<gray>Price<dark_gray>: <gold><price><gray>
"""
unlocked_with_rank = """
<gray>Unlocked with the <rank_color><rank> rank</rank_color><br>
<gray>obtainable on <gold>store.kitpvp.world<gray>.
"""
upgradable_armor = """
<gray>Buyable in the <gold>cosmetics store</gold><br>
<gray>By upgrading your armor<gray>
"""

[gui.cosmetics.armorUpgrade]
title = "Upgrade Armor"
upgradeTo = "<gold>Upgrade To <level>"
upgradeTo.lore = """
<gray>Price<dark_gray>: <gold><price>
"""
fully = "<sec>Fully Upgraded!"

level.chain = "Chain"
level.gold = "Gold"
level.iron = "Iron"
level.diamond = "Diamond"
level.netherite = "Netherite"

[cosmetics.category]
ranks = "<red>Rank Cosmetics"
hats="<aqua>Hats"
pets="<blue>Pets"
mounts="<yellow>Mounts"
particles="<gold>Particle Overview"
trail_particles="<gold>Trails"
join_particles="<gold>Join Particle"
kill_particles="<gold>Kill Particle"
mystic_particles="<light_purple>Mysterious Particles"
gadgets="<dark_green>Gadgets"
armor="<yellow>Wardrobe"
effects="<color:#ffd8ad>Effects"
abilities="<green>Abilities"
balloons="<light_purple>Balloons"

[cosmetics.rarity]
common = "Common"
rare = "Rare"
epic = "Epic"
legendary = "Legendary"
rank_champ = "Champ Rank"
rank_grand_champ = "Grand Champ Rank"
rank_ultra = "Ultra Rank"

[cosmetics.hats]
astronaut="Astronaut Hat"
astronaut.lore="""
    <color:#00FF7F>Free<br>
    <gray>on <gold>store.kitpvp.world<gray>.
"""
feather="Feather Hat"
feather.lore="""
    <color:#00FF7F>Free<br>
    <gray>on <gold>store.kitpvp.world<gray>.
"""

[cosmetics.pets]
blaze = "Blaze"
fox = "White Fox"
wolf = "Dog"
cat = "Cat"
rabbit = "Bunny"
panda="Baby Panda"
sheep = "Sheep"
cow = "Cow"
chicken = "Chicken"
slime = "Slime"
pig = "Pig"
turtle = "Turtle"
silverfish = "Silverfish"

[cosmetics.mounts]
flying_squid="Flying Squid"
teleporting_enderman="Teleporting Enderman"
climbing_cave_spider="Climbing Cave Spider"
iron_golem="Iron Golem"
panda="Panda"
horse="Horse"
magma_cube="Magma Cube"

[cosmetics.trail_particles]
ultra="<red>Ultra Trail"
grand_champ="<aqua>Grand Champ Trail"
champ="<gold>Champ Trail"
hearts="Hearts Trail"
cherry_blossom="Cherry Blossom Trail"
cherry_blossom.lore="""
<color:#00FF7F>Included<br>
<gray>on <gold>store.kitpvp.world<gray>.
"""

[cosmetics.join_particles]
ultra="<red>Ultra Join Particle"
grand_champ="<aqua>Grand Champ Join Particle"
champ="<gold>Champ Join Particle"

[cosmetics.kill_particles]

[cosmetics.gadgets]
grappling_hook="Grappling Hook"
enderman_mount = "Teleport"
enderman_mount.max = "You can only teleport <underlined>20 blocks</underlined> maximally."

[cosmetics.armor]
ultra = "<red>Ultra Armorset"
grand_champ = "<aqua>Grand Champ Armorset"
champ = "<gold>Champ Armorset"
netherite = "Netherite Armorset"
diamond = "Diamond Armorset"
iron = "Iron Armorset"
gold = "Golden Armorset"
chain = "Chainmail Armorset"

piece.helmet = "Helmet"
piece.chestplate = "Chestplate"
piece.leggings = "Leggings"
piece.boots = "Boots"

[cosmetics.effects]
speed="Speed"
jump_boost="Jump Boost"
slow_falling="Slow Falling"

[cosmetics.abilities]
double_jump="Double Jump"
flight = "Flight"


[cosmetics.balloons]
ultra="<red>Ultra Balloon"
grand_champ="<aqua>Grand Champ Balloon"
champ="<gold>Champ Balloon"
orange="Orange Balloon"
red="Red Balloon"
purple="Purple Balloon"
pink="Pink Balloon"
light_pink="Light Pink Balloon"
white="White Balloon"
light_gray="Light Gray Balloon"
yellow="Yellow Balloon"
lime="Lime Balloon"
green="Green Balloon"
light_blue="Light Blue Balloon"

[gui.boosters]
use = "Used <type><reset>, you will now gain <rarity_color><multiplier>%%<reset> more <unit_type> for <duration><reset>."
use.active = "You already have an <type><reset> active."
use.fail = "Failed to use the booster. Is it already used?"
item.lore = """
    <gray>Rarity</gray><dark_gray>:</dark_gray> <rarity><reset><br>
    <gray>Multiplier</gray><dark_gray>:</dark_gray> <rarity_color><multiplier></rarity_color><br>
    <gray>Duration</gray><dark_gray>:</dark_gray> <rarity_color><duration></rarity_color>
"""
