[error]
notEnoughPlayers = "Not enough players online."
border = "Out of border"
noGame = "<red>No game found"

[phases]
start = "<green>Let the fight begin."
border = "The border begins to shrink. The fight ends in <minutes_left> minutes."
stop = "<red>Game ended."

[event]
player.leave = "<pri><name><reset> left the duel."
player.join = "<pri><name><reset> joined the duel."
player.spectate = "<pri><name> <reset>is spectating."
win = """
<team>
<br><yellow>has won!
"""
win.firstTo = """
<gray>Round <round><reset>
<br><aqua><self_points><dark_gray> - <red><opponent_points>
"""
win.firstTo.end = """
<team><reset><yellow> has won
<br><aqua><self_points><dark_gray> - <red><opponent_points>
"""


[win]
stats = """
  <br>Damage taken: <aqua><damage_taken_self></aqua>/<red><damage_taken_opponent></red>
  <br>Health remaining: <aqua><health_self>❤</aqua>/<red><health_opponent>❤</red>
  <br>Hits taken: <aqua><hits_taken_self></aqua>/<red><hits_taken_opponent></red>
  <br>Crits taken: <aqua><crits_taken_self></aqua>/<red><crits_taken_opponent></red>
"""
elo = "<winner> (<winnerelo>) (+<winnerelodifference>) <reset>has defeated <red><loser> (<loserelo>) (<loserelodifference>) <reset>in Kit <kit><reset>."
single = "In an epic battle against life and death, <pri><name> <reset> won."

[features]
inventory = "<aqua>Inventory"
teleport = "<yellow>Teleport"
leave = "<red>Leave"

[commands.game]
error.minimum = "There must be at least two players in a duel."
start = "Starting game <game_id>"

[gui.selectInventory]
title = "Select Player"

[gui.teleport]
title = "Teleport"
