[error]
notEnoughPlayers = "Not enough players online."
border = "Out of border"
noGame = "<red>No game found"

[phases]
start = "<green>Let the fight begin."
border = "The border begins to shrink. The fight ends in <minutes_left> minutes."
stop = "<red>Game ended."

[event]
player.leave = "<pri><name><reset> left the duel."
player.join = "<pri><name><reset> joined the duel."
player.spectate = "<pri><name> <reset>is spectating."
win = """
<team>
<br><yellow>has won!
"""
win.firstTo = """
<gray>Round <round><reset>
<br><aqua><self_points><dark_gray> - <red><opponent_points>
"""
win.firstTo.end = """
<team><reset><yellow> has won
<br><aqua><self_points><dark_gray> - <red><opponent_points>
"""
# We have to use %s here to use the targets users' MiniMessages
winstreak = "%s<reset> reached a <#00FF7F><bold><winstreak></bold>x winstreak<reset> in <kit><reset>."

[kit.record]
core.health_remaining = "Health remaining"
core.damage_taken = "Damage taken"
core.hits_taken = "Hits taken"
core.crits_taken = "Crits taken"
core.totems_remaining = "Totems remaining"
core.xp_bottles_remaining = "XP Bottles remaining"
uhc.lava_damage_taken = "Lava Damage taken"
uhc.projectile_damage_taken = "Arrow Damage taken"
uhc.golden_apple_remaining = "Gaps remaining"
crystal.crystal_damage_taken = "Crystal Damage taken"
crystal.anchor_damage_taken = "Anchor Damage taken"
nethpot.health_potions_remaining = "Health Potions remaining"
axe.sword_hits = "Hits with Sword"
axe.axe_hits = "Hits with Axe"
axe.arrows_remaining = "Arrows remaining"
smp.potions_remaining = "Overall Potions remaining"

[win]
elo = "<winner> <reset><is_solo_game:has:have> defeated <red><loser> <reset>in Kit <kit><reset>."
single = "In an epic battle against life and death, <pri><name> <reset> won."

[features]
inventory = "<aqua>Inventory"
teleport = "<yellow>Teleport"
leave = "<red>Leave"

[commands.game]
error.minimum = "There must be at least two players in a duel."
start = "Starting game <game_id>"

[gui.selectInventory]
title = "Select Player"

[gui.teleport]
title = "Teleport"
