[hotbar]
challenge = "<gray>Challenge"
clan = "<yellow>Clan"
items = "<gold>Items"
friends = "<green>Friends"
language = "<red>Language"
lobby = "<aqua>Lobby"

nick.nicked = "<gray>You are <dark_gray>: <green>nicked"
nick.unnicked = "<gray>You are<dark_gray>: <red>not nicked"
nick.development = "This feature is currently in development."

[gui.lobbySwitcher]
title = "Lobby Wechseln"
premium = "The server you are trying to connect to requires you to have at least the <gold>Premium rank</gold>."

[gui.kitLayout]
saved = "The kit layout has been saved."
error = "An error occurred. Please try again or contact support."
reset = "Reset"

[scoreboard]
clan = """
  <br>Clan<gray>:
  <br><gray><clan>
  <br>
  <br>Clan Elo<gray>:
  <br><gray><clanelo>
  <br>
  <br>Clan Level<gray>:
  <br><gray><clanlevel>★
  <br>
  <br>Clan Coins<gray>:
  <br><gold><clancoins>
  <br>
  <br>Clan Members<gray>:
  <br><aqua><onlineclanmembers><gray>/<dark_gray><totalclanmembers>
"""

self = """
  <br>Rank<gray>:
  <br><rank>
  <br>
  <br>Elo<gray>:
  <br><gray><elo>
  <br>
  <br>Playtime<gray>:
  <br><yellow><hours>h
  <br>
  <br>Coins<gray>:
  <br><gold><coins>
  <br>
  <br>Friends<gray>:
  <br><green><onlinefriends><gray>/<dark_gray><totalfriends>
"""

selfSecondary = """
  <br>Rank<gray>:
  <br><rank>
  <br>
  <br>Elo<gray>:
  <br><gray><elo>
  <br>
  <br>Level<gray>:
  <br><level>
  <br>
  <br>Coins<gray>:
  <br><gold><coins>
  <br>
  <br>Friends<gray>:
  <br><green><onlinefriends><gray>/<dark_gray><totalfriends>
"""

[features]
levelup.title = """
  <green>Level Up!
  <br><level> <gray>→ <new_level>
"""
discord = "Join <click:open_url:'https://dc.kitpvp.world'><color:#5865f2>our Discord</color>: <dark_gray>[<sec>Click Here</sec>]</dark_gray></click>"
