[hotbar]
challenge = "<gray>Challenge"
party.member = "<purple>Party"
party.moderator = "<purple>Moderate Party"
party.leader = "<purple>Manage Party"
party.none = "<gray>In No Party"
items = "<gold>Items"
friends = "<green>Friends"
language = "<red>Language"
kiteditor = "<red>Kit Editor"
lobby = "<aqua>Lobby"

nick.nicked = "<gray>You are <dark_gray>: <green>nicked"
nick.unnicked = "<gray>You are<dark_gray>: <red>not nicked"
nick.development = "This feature is currently in development."

[gui.kitLayout]
saved = "The kit layout for <kit><reset> has been saved."
error = "An error occurred. Please try again or contact support."
reset = "Reset"
reset.confirm = "Confirm Reset"
reset.cancel = "Cancel Reset"
select.title = "Kit Layout: Select Kit"

[gui.lobbySwitcher]
title = "Lobby Wechseln"
champ = "The server you are trying to connect to requires you to have at least the <gold>Champ rank</gold>."
connected = " (Connected)"
connectTo.lore = "<gray>Connect to this lobby after the duel by default"

[leaderboard]
loading = "Die Leaderboard is still loading! It can take up to three seconds."

[scoreboard]
clan = """
  <br>Clan<gray>:
  <br><gray><clan>
  <br>
  <br>Clan Elo<gray>:
  <br><gray><clanelo>
  <br>
  <br>Clan Level<gray>:
  <br><gray><clanlevel>★
  <br>
  <br>Clan Coins<gray>:
  <br><gold><clancoins>
  <br>
  <br>Clan Members<gray>:
  <br><aqua><onlineclanmembers><gray>/<dark_gray><totalclanmembers>
"""

self = """
  <br>Rank<gray>:
  <br><rank>
  <br>
  <br>Elo<gray>:
  <br><gray><elo>
  <br>
  <br>Playtime<gray>:
  <br><yellow><hours>h
  <br>
  <br>Coins<gray>:
  <br><gold><coins>
  <br>
  <br>Friends<gray>:
  <br><green><onlinefriends><gray>/<dark_gray><totalfriends>
"""

selfSecondary = """
  <br>Rank<gray>:
  <br><rank>
  <br>
  <br>Elo<gray>:
  <br><gray><elo>
  <br>
  <br>Level<gray>:
  <br><level>
  <br>
  <br>Coins<gray>:
  <br><gold><coins>
  <br>
  <br>Friends<gray>:
  <br><green><onlinefriends><gray>/<dark_gray><totalfriends>
"""

[features]
levelup.title = """
  <green>Level Up!
  <br><level> <gray>→ <new_level>
"""
discord = "Join <click:open_url:'https://discord.gg/JEYwEcRHnw'><color:#5865f2>our Discord</color>: <dark_gray>[<sec>Click Here</sec>]</dark_gray></click>"
store = "<click:open_url:'https://store.kitpvp.world'>Hey, if you like our projects so far and You want to support us on our future projects, consider purchasing a Rank on <gold><bold>store.kitpvp.world</bold></gold> :)"
bots = "PvP Bots will release on 24th of December."
version = "For the best experience, play on the version <version>"