[commands.connection]
build = "You will be connected to the <pri>Build Server<reset>."
noService = "No service found."

[commands.duel]
norequest = "You have not received a request from this player."
self = "Sorry, why would you want to fight against yourself? That's Stats-Boosting!"
partyDuelStatus = "(Party of <members> players)"
requestReceived = """
  <pri><user><reset> challenges you in <kit><reset>.
  <br><green><click:run_command:'/duel %1$s accept'>[<bold>✔ Accept</bold>]</click></green>
  <red> <click:run_command:'/duel %1$s decline'>[<bold>❌ Deny</bold>]</click></red>
"""
requestReceived.firstTo = """
  <pri><user><reset> challenges you in <kit><reset> <yellow>FT<first_to><reset>.
  <br><green><click:run_command:'/duel %1$s accept'>[<bold>✔ Accept</bold>]</click></green>
  <red> <click:run_command:'/duel %1$s decline'>[<bold>❌ Deny</bold>]</click></red>
"""
requestSent = "You have challenged <pri><target><reset> in <kit><reset>."
requestSent.firstTo = "You have challenged <pri><target><reset> in <kit><reset> <yellow>FT<first_to><reset>."

decline = "You declined the request."
accept = "You accepted <pri><name>'s<reset> request."

[commands.spectate]
noRunningGame = "This player is currently not playing."

[gui.challenge]
title = "Challenge"
firstTo = "<gray>First To<dark_gray>: <green><rounds>"
showHealth_true = "<gray>Show Health<dark_gray>: <sec>Enabled"
showHealth_false = "<gray>Show Health<dark_gray>: <red>Disabled"
showHealth_not_set = "<gray>Show Health<dark_gray>: <pri>Kit Default"
custom = "<gray>Custom Kit<dark_gray>: <yellow><kit>"
custom.unselected = "You do not have a kit selected!"

[gui.mapSelection]
title = "Map Selection"

[gui.queueSettings]
partyMode.only_solo = "<blue>Only Solos"
partyMode.only_solo.lore = """
<gray>Only play 1v1 games
"""
partyMode.only_party = "<sec>Only Parties"
partyMode.only_party.lore = """
<gray>Only play team games and be<br>
<gray>matched into a team with another solo"""
partyMode.both = "<sec>Party and Solo"
partyMode.both.lore = """
<gray>Play 1v1 or team games, where you are<br>
<gray>matched into a team with another solo
"""
partyMode.locked_party = "<sec>Only Party (Locked)"
partyMode.locked_party.lore = """
<gray>You are in a party and therefore<br>
<gray>can only play against other parties.
"""

[gui.quickQueue]
title = "Queues"
status = """
<sec>Playing<dark_gray>: <sec><playing><br>
<pri>Queuing<dark_gray>: <pri><queuing><br>
<br>
<gray>Click to play!
"""

[gui.botSelection]
title = "Select Bot"
play = "Play"
easy = "Easy Bot"
advanced = "Advanced Bot"
hard = "Difficult Bot"
impossible = "Impossible Bot"

[gui.botSettings]
title = "Bot Settings"
range = "<gray>Range<dark_gray>: <gray><range>"
endless = "<aqua>Endless"

[queue]
join = "You have <sec>entered</sec> the <pri><queue><reset>."
leave = "You <red>left</red> the <pri><queue><reset>."
already = "You are already in the <pri><queue><reset> queue."
matchFound = "A match was found."
inNone = "You weren't in any queue."
noGameServer = "Trying to start the game failed: There are no game servers available. Please try again later."
noArenaFound = "You have disabled too many arenas, and we could not find an arena for this match. Please, enable arenas for <kit><reset> again."
disablingArenasNotice = "Disabling arenas can cause slower queue waiting times or not finding any games."
atLeastOneArenaEnabled = "You must keep at least one arena active."
userUnavailable = "<username><reset> is unavailable."
partyTooBig = "Your party has too many members (<members>/<max_members>). You cannot join the queue."

[queue.block]
newAccount = "Your account is too new. Play <pri><games_remaining> more unranked games</pri> to play ranked."
alt = "This account has been blocked and can only play unranked. Just play on your Main Account, <main_account>. If you think this is a bug, open a ticket on <click:open_url:'https://discord.gg/JEYwEcRHnw'><color:#5865f2>our Discord</color></click>."
ban = "You were banned from the ranked queue for <duration><reset>. Therefore, you can only play unranked."
ban.permanent = "You were <red>›PERMANENTLY‹</red> banned from the ranked queue. Therefore, you can only play unranked."
ban.season = "You were banned from the ranked queue for this season. Therefore, you can only play unranked."
time = "Ranked is from 3 AM to 7 AM <bold>disabled</bold>. It's <time>."
error = "Loading ranked queue failed. Try rejoining the server and report this issue in our support."

[commands.queue.arena_settings]
set = "<value:'<sec>Enabled</sec>':'<red>Disabled</red>'> arena <pri><arena></pri> for the kit <kit>."

[games.party]
join = "<username><reset> <sec>joined</sec> your party."
leave = "<username><reset> <red>left</red> your party."

joinMe = """
Join Me:<br>
<username><reset> opened their party! [<members>/<max_members>]<br>
<click:run_command:'/party join %s'><dark_gray>[<sec><bold>Click Here</bold></sec>]</dark_gray> To Join<br>
"""
joinMe.notPublic = "Your party is not public. <click:suggest_command:/party open><dark_gray>[<pri><bold>/party open</bold></pri>]</click>"
joinMe.cooldown = "You must wait <yellow><remaining_minutes> minutes</yellow> before you can create a Join Me again."

memberRoleChanged.leader = "<username><reset> is now the <#ff2e58>party leader</#ff2e58>."
memberRoleChanged.moderator = "<username><reset> is now a <#8157ff>party moderator</#8157ff>."
memberRoleChanged.member = "<username><reset> is now <#5ea1ff>party member</#5ea1ff>."

public = "Your party is now <sec>public</sec>."
private = "Your party is now <yellow>private</yellow>."

disband = "<username><reset> <red>disbanded</red> the party."

invite = "<username><reset> is <sec>invited</sec> to join the party. They have five minutes to accept the invite."
invite.already = "<username><reset> is already invited to your party."
invited = """
<username><reset> invited you to join their party.
<br><dark_gray><click:run_command:'/party accept %1$s'>[<sec><bold>✔ Accept</bold></sec>]</click> <click:run_command:'/party decline %1$s'>[<red><bold>❌ Decline</bold></red>]</click></dark_gray>
"""

accept = "<sec>Accepted</sec> the party invite by <party_leader><reset>."
accept.inGame = """
You are currently in a game. If you join the party, you can be moved out of the match.<br>
<br<yellow><confirm_action>[<bold>Accept Risk and Continue</bold>]</confirm_action></yellow>
"""
accept.none = "You are not invited to join <party_leader>'s party."
accept.alreadyInParty = "You are already in another party."
accept.alreadyInThisParty = "You are already in this party."
decline = "<red>Declined</red> the party invite by <party_leader>."
declined = "<username><reset> declined the party invite."

join.notPublic = "<username><reset> is in no public party."

demote.member = "<username><reset> is already an <#5ea1ff>party member</#5ea1ff>, cannot demote them further!"

spectate = "Joining <#ff2e58>party leader's</#ff2e58> match."
spectate.notInGame = "The <#ff2e58>party leader</#ff2e58> is not in any match."

duel = "<username><reset> is starting a party duel in <kit><reset> on arena <arena><reset>."

listMembers = "Showing party members (<members_count>/<max_members>): <br><members>"

[games.party.memberRole]
member = "<#5ea1ff>Party Member</#5ea1ff>"
moderator = "<#8157ff>Party Moderator</#8157ff>"
leader = "<#ff2e58>Party Leader</#ff2e58>"

[games.party.error]
permission.leader = "This action requires you to be the <#ff2e58>party leader</#ff2e58>!"
permission.moderator = "This action requires you to be a <#8157ff>party moderator</#8157ff>!"
inNoParty = "You are not a member of any party!"
chatMessageTooLong = "Your chat message is too long!"
targetMember = "<username><reset> is not a member of your party!"
moderateSelf = "Cannot moderate yourself!"
duelPartyMember = "Cannot duel <target><reset> because he is in a party and not the <#ff2e58>party leader</#ff2e58>."
inGame = "This command is not allowed while in a game."
maxMembers = "The party reached the maximum of <max_members> members."

[gui.partyDuel]
title = "<#5ea1ff>Party Duel"