[commands.connection]
build = "You will be connected to the <pri>Build Server<reset>."
noService = "No service found."

[commands.duel]
norequest = "You have not received a request from this player."
self = "Sorry, why would you want to fight against yourself? That's Stats-Boosting!"
requestReceived = """
  <pri><user><reset> challenges you in <kit><reset>.
  <br><green><click:run_command:'/duel %1$s accept'>[<bold>✔ Accept</bold>]</click></green>
  <red> <click:run_command:'/duel %1$s decline'>[<bold>❌ Deny</bold>]</click></red>
"""
requestReceived.firstTo = """
  <pri><user><reset> challenges you in <kit><reset> <yellow>FT<first_to><reset>.
  <br><green><click:run_command:'/duel %1$s accept'>[<bold>✔ Accept</bold>]</click></green>
  <red> <click:run_command:'/duel %1$s decline'>[<bold>❌ Deny</bold>]</click></red>
"""
requestSent = "You have challenged <pri><target><reset> in <kit><reset>."
requestSent.firstTo = "You have challenged <pri><target><reset> in <kit><reset> <yellow>FT<first_to><reset>."

decline = "You declined the request."
accept = "You accepted <pri><name>'s<reset> request."

[commands.spectate]
noRunningGame = "This player is currently not playing."

[gui.challenge]
title = "Challenge"
firstTo = "<gray>First To<dark_gray>: <green><rounds>"
showHealth_true = "<gray>Show Health<dark_gray>: <sec>Enabled"
showHealth_false = "<gray>Show Health<dark_gray>: <red>Disabled"
showHealth_not_set = "<gray>Show Health<dark_gray>: <pri>Kit Default"
custom = "<gray>Custom Kit<dark_gray>: <yellow><kit>"
custom.unselected = "You do not have a kit selected!"

[gui.mapSelection]
title = "Map Selection"

[gui.quickQueue]
title = "Queues"
status = """
<sec>Playing<dark_gray>: <sec><playing><br>
<pri>Queuing<dark_gray>: <pri><queuing><br>
<br>
<gray>Click to play!
"""

[gui.botSelection]
title = "Select Bot"
play = "Play"
easy = "Easy Bot"
advanced = "Advanced Bot"
hard = "Difficult Bot"
impossible = "Impossible Bot"

[gui.botSettings]
title = "Bot Settings"
range = "<gray>Range<dark_gray>: <gray><range>"
endless = "<aqua>Endless"

[queue]
join = "You have <sec>entered</sec> the <pri><queue><reset>."
leave = "You <red>left</red> the <pri><queue><reset>."
already = "You are already in the <pri><queue><reset> queue."
matchFound = "A match was found."
inNone = "You weren't in any queue."
noGameServer = "Trying to start the game failed: There are no game servers available. Please try again later."
noArenaFound = "You have disabled too many arenas, and we could not find an arena for this match. Please, enable arenas for <kit><reset> again."
disablingArenasNotice = "Disabling arenas can cause slower queue waiting times or not finding any games."
atLeastOneArenaEnabled = "You must keep at least one arena active."
userUnavailable = "<username><reset> is unavailable."

[queue.block]
newAccount = "Your account is too new. Play <pri><games_remaining> more unranked games</pri> to play ranked."
alt = "This account has been blocked and can only play unranked. Just play on your Main Account, <main_account>. If you think this is a bug, open a ticket on <click:open_url:'https://discord.gg/JEYwEcRHnw'><color:#5865f2>our Discord</color></click>."
ban = "You were banned from the ranked queue for <duration><reset>. Therefore, you can only play unranked."
ban.permanent = "You were <red>›PERMANENTLY‹</red> banned from the ranked queue. Therefore, you can only play unranked."
ban.season = "You were banned from the ranked queue for this season. Therefore, you can only play unranked."
time = "Ranked is from 3 AM to 7 AM <bold>disabled</bold>. It's <time>."
error = "Loading ranked queue failed. Try rejoining the server and report this issue in our support."

[commands.queue.arena_settings]
set = "<value:'<sec>Enabled</sec>':'<red>Disabled</red>'> arena <pri><arena></pri> for the kit <kit>."