[commands.connection]
build = "You will be connected to the <pri>Build Server<reset>."
noService = "No service found."

[commands.duel]
norequest = "You have not received a request from this player."
self = "Sorry, why would you want to fight against yourself? That's Stats-Boosting!"
requestReceived = """
  <pri><user><reset> challenges you in <kit><reset>.
  <br><green><click:run_command:'/duel %1$s accept'>[<bold>✔ Accept</bold>]</click></green>
  <red> <click:run_command:'/duel %1$s decline'>[<bold>❌ Deny</bold>]</click></red>
"""
requestReceived.firstTo = """
  <pri><user><reset> challenges you in <kit><reset> <yellow>FT<first_to><reset>.
  <br><green><click:run_command:'/duel %1$s accept'>[<bold>✔ Accept</bold>]</click></green>
  <red> <click:run_command:'/duel %1$s decline'>[<bold>❌ Deny</bold>]</click></red>
"""
requestSent = "You have challenged <pri><target><reset> in <kit><reset>."
requestSent.firstTo = "You have challenged <pri><target><reset> in <kit><reset> <yellow>FT<first_to><reset>."

decline = "You declined the request."
accept = "You accepted <pri><name>'s<reset> request."

[commands.spectate]
noRunningGame = "This player is currently not playing."

[gui.challenge]
title = "Challenge"
firstTo = "<gray>First To<dark_gray>: <green><rounds>"
custom = "<gray>Custom Kit<dark_gray>: <yellow><kit>"
custom.unselected = "You do not have a kit selected!"

[gui.mapSelection]
title = "Map Selection"

[gui.quickQueue]
title = "Queues"
status = """
<sec>Playing<dark_gray>: <sec><playing><br>
<pri>Queuing<dark_gray>: <pri><queuing><br>
<br>
<gray>Click to play!
"""

[gui.botSelection]
title = "Select Bot"
play = "Play"
easy = "Easy Bot"
advanced = "Advanced Bot"
hard = "Difficult Bot"
impossible = "Impossible Bot"

[gui.botSettings]
title = "Bot Settings"
range = "<gray>Range<dark_gray>: <gray><range>"
endless = "<aqua>Endless"

[queue]
join = "You have entered the <pri><queue><reset>."
leave = "You left the <pri><queue><reset>."
matchFound = "A match was found."
inNone = "You weren't in any queue."
noGameServer = "Trying to start the game failed: There are no game servers available. Please try again later."
noArenaFound = "You have disabled too many arenas and we could not find an arena for this match. Please, enable arenas for <kit><reset> again."
disablingArenasNotice = "Disabling arenas can cause slower queue waiting times or not finding any games."
atLeastOneArenaEnabled = "You must keep at least one arena active."

[queue.block]
newAccount = "Your account is too new. Wait <pri><minutes_remaining> minutes</pri> to play ranked."
alt = "This account has been blocked and can only play unranked. Just play on your Main Account. If you think this is a bug, open a ticket on <click:open_url:'https://discord.gg/JEYwEcRHnw'><color:#5865f2>our Discord</color></click>."

[commands.queue.arena_settings]
set = "<value:'<sec>Enabled</sec>':'<red>Disabled</red>'> arena <pri><arena></pri> for the kit <kit>."