[commands.connection]
build = "You will be connected to the <pri>Build Server<reset>."

[commands.duel]
norequest = "You have not received a request from this player."
self = "Sorry, why would you want to fight against yourself? That's Stats-Boosting!"
requestReceived = """
  <pri><user><reset> challenges you in <kit><reset>.
  <br><green><click:run_command:'/duel %1$s accept'>[<bold>✔ Accept</bold>]</click></green>
  <red> <click:run_command:'/duel %1$s decline'>[<bold>❌ Deny</bold>]</click></red>
"""
requestReceived.firstTo = """
  <pri><user><reset> challenges you in <kit><reset> <yellow>FT<first_to><reset>.
  <br><green><click:run_command:'/duel %1$s accept'>[<bold>✔ Accept</bold>]</click></green>
  <red> <click:run_command:'/duel %1$s decline'>[<bold>❌ Deny</bold>]</click></red>
"""
requestSent = "You have challenged <pri><target><reset> in <kit><reset>."
requestSent.firstTo = "You have challenged <pri><target><reset> in <kit><reset> <yellow>FT<first_to><reset>."

decline = "You declined the request."
accept = "You accepted <pri><name>'s<reset> request."

[gui.challenge]
title = "Challenge"
firstTo = "<gray>First To<dark_gray>: <green><rounds>"
custom = "<gray>Custom Kit<dark_gray>: <yellow><kit>"
custom.unselected = "You do not have a kit selected!"

[queue]
join = "You have entered the <pri><queue><reset>."
leave = "You left the <pri><queue><reset>."
matchFound = "A match was found."
inNone = "You weren't in any queue."
block = "This account has been blocked and can only play unranked. Just play on your Main Account. If you think this is a bug, open a ticket on <click:open_url:'https://dc.kitpvp.world'><color:#5865f2>our Discord</color></click>."
noGameServer = "Trying to start the game failed: There are no game servers available. Please try again later."
