[gui.profile]
title = "<red>Profile"
achievements = "Coming Soon"
next.lore = "<yellow>to season <season>"
previous.lore = "<yellow>to season <season>"
head.lore = """
    <rank><reset>
    <br><level><reset> 
"""

globalItem = """
    <gray>Rank<dark_gray>: <elorank>
    <br><gray>Elo<dark_gray>: <elo>
    <br><gray>Highest Elo<dark_gray>: <topelo>
    <br>
    <br><gray>Games played<dark_gray>: <yellow><gamesplayed>
    <br><gray>Games won<dark_gray>: <yellow><gameswon>
    <br>
    <br><gray>Winstreak<dark_gray>: <yellow><winstreak>
    <br><gray>Highest Winstreak<dark_gray>: <yellow><topwinstreak>
    <br>
    <br><gray>Playtime<dark_gray>: <yellow><playtime>
"""

kitItem = """
    <gray>Rank<dark_gray>: <elorank>
    <br><gray>Elo<dark_gray>: <elo>
    <br><gray>Highest Elo<dark_gray>: <topelo>
    <br>
    <br><gray>Games played<dark_gray>: <yellow><gamesplayed>
    <br><gray>Games won<dark_gray>: <yellow><gameswon>
    <br>
    <br><gray>Winstreak<dark_gray>: <yellow><winstreak>
    <br><gray>Highest Winstreak<dark_gray>: <yellow><topwinstreak>
"""
