[store.category]
ranks="Ranks"
xp_booster="XP Booster"
coins_booster="Coins Booster"
more="More Stuff"

[store.category.ranks]
champ="Champ"
ultra="Ultra"
grandChamp="Grand Champ"

[store.category.ranks.key]
usernameColor="Username Color"
usernameColor.gold="Gold"
usernameColor.aqua="Aqua"
usernameColor.red="Red"
specialNameplate="Special Nameplate"
specialChatIcon="Special Chat Icon"
noChatCooldown="No Chat Cooldown"
colorizedGG="Colorized GG"
earlyAccess="Early Access"
friendStatus="Friend Status"
champLobby="Access To Champ Lobby"
pvpBots2vs2="PvP Bots 2vs2"
rankSpecificCosmetics="Rank Specific Cosmetics"
mapSelection="Map Selection"
accessToReplay="Access To Replays"
publicParties="Public Parties"
fly="Fly in Lobby"
extendedReplayAccess="Extended Replay Access"
extendedReplayAccess.3d="3 Days"
extendedReplayAccess.7d="7 Days"
replaySaveSlots="Replay Save Slots"
clanMemberIncrease="Clan Member Increase"
coinXpBoost="Coin & XP Boost"
partySize="Max Party Size"
friendSlots="Max Friends"
pvpBotsSaveSlots="PvP Bots Preset Slots"
dailyRewardChest="Bonus Daily Reward Chests"
dailyRewardCoins="Bonus Daily Reward Coins"

[store.category.xp_booster]
xpBooster8h4x="XP Booster 400%% - 8h"
xpBooster8h4x.description="""
<b>The 8h XP Boost contains:</b>
<ul>
    <li>A 8h XP Boost which increases the XP you gain by 400%%.</li>
</ul>

<i>XP Boosters are virtual items that increase the experience points (XP) you earn, helping you level up faster. They provide no gameplay advantages beyond faster leveling and can be managed through your inventory.</i>
"""
xpBooster3d4x="XP Booster 400%% - 3d"
xpBooster3d4x.description="""
<b>The 3d XP Boost contains:</b>
<ul>
    <li>A 3d XP Boost which increases the XP you gain by 400%%.</li>
</ul>

<i>XP Boosters are virtual items that increase the experience points (XP) you earn, helping you level up faster. They provide no gameplay advantages beyond faster leveling and can be managed through your inventory.</i>
"""
xpBooster7d4x="XP Booster 400%% - 7d"
xpBooster7d4x.description="""
<b>The 7d XP Boost contains:</b>
<ul>
    <li>A 7d XP Boost which increases the XP you gain by 400%%.</li>
</ul>

<i>XP Boosters are virtual items that increase the experience points (XP) you earn, helping you level up faster. They provide no gameplay advantages beyond faster leveling and can be managed through your inventory.</i>
"""
usageDescription="""
XP Booster can be activated in the XP Booster GUI, which you can access with "/booster xp" or over the Cosmetics GUI and then on XP Booster, which you can access with the "/cosmetics" command or over your 5th slot in the lobby.
"""

[store.category.coins_booster]
coinsBooster8h4x="Coins Booster 400%% - 8h"
coinsBooster8h4x.description="""
<span class="font-semibold">The package [8h Coins Boost] contains:</span>
<ul class="list-disc list-inside">
    <li class="font-medium">A 8h Coin Boost which increases the coins you gain by 400%%.</li>
</ul>

<i class="font-light">Coins are a virtual currency used on KitPvP.world to purchase various cosmetic items and upgrades. They hold no real-world value (thus cannot be paid out) and do not provide any competitive gameplay advantages.</i>
"""
coinsBooster3d4x="Coins Booster 400%% - 3d"
coinsBooster3d4x.description="""
<span class="font-semibold">The package [3d Coins Boost] contains:</span>
<ul class="list-disc list-inside">
    <li class="font-medium">A 3d Coin Boost which increases the coins you gain by 400%%.</li>
</ul>

<i class="font-light">Coins are a virtual currency used on KitPvP.world to purchase various cosmetic items and upgrades. They hold no real-world value (thus cannot be paid out) and do not provide any competitive gameplay advantages.</i>
"""
coinsBooster7d4x="Coins Booster 400%% - 7d"
coinsBooster7d4x.description="""
<span class="font-semibold">The package [7d Coins Boost] contains:</span>
<ul class="list-disc list-inside">
    <li class="font-medium">A 7d Coin Boost which increases the coins you gain by 400%%.</li>
</ul>

<i class="font-light">Coins are a virtual currency used on KitPvP.world to purchase various cosmetic items and upgrades. They hold no real-world value (thus cannot be paid out) and do not provide any competitive gameplay advantages.</i>
"""
usageDescription="""
Coin Booster can be activated in the Coin Booster GUI, which you can access with "/booster coins" or over the cosmetics GUI and then on Coin Booster, which you can access with the /cosmetics command or over your 5th slot in the lobby.
"""

[store.category.more]
hatAstronaut="Astronaut Hat"
hatAstronaut.description="""
<span class="font-semibold">The Astronaut Helmet Package contains:</span>
<ul class="list-disc list-inside">
    <li class="font-medium">Astronaut Helmet</li>
</ul>

<i class="font-light">Cosmetics are virtual wearable items that allow you to customize your in-game appearance. They offer no gameplay advantages and can be accessed through your Items slot in the Lobby.</I>
"""
hatFeather="Feather Hat"
hatFeather.description="""
<span class="font-semibold">The Feather Helmet Package contains:</span>
<ul class="list-disc list-inside">
    <li class="font-medium">Feather Helmet</li>
</ul>

<i class="font-light">Cosmetics are virtual wearable items that allow you to customize your in-game appearance. They offer no gameplay advantages and can be accessed through your Items slot in the Lobby.</I>
"""
trailCherryBlossom="Cherry Blossom Trail"
trailCherryBlossom.description="""
<span class="font-semibold">The Cherry Blossom Trail Package contains:</span>
<ul class="list-disc list-inside">
    <li class="font-medium">Cherry Blossom Trail</li>
</ul>

<i class="font-light">Cosmetics are virtual wearable items that allow you to customize your in-game appearance. They offer no gameplay advantages and can be accessed through your Items slot in the Lobby.</I>
"""
usageDescription="""
Cosmetics can be selected with the "/cosmetics" command or the 5th slot in the Lobby.
"""

[store.actions]
free="Free"
view="View"

[store.dialog]

[store.dialog.support]
title="Support"
description="""
Wir bieten gerade nur den Support über <a href="mailto:support@kitpvp.world"><strong>unsere E-Mail</strong></a> oder <a href="https://dc.kitpvp.world">auf unserem öffentlichen <strong>Discord</strong> Server</a> an.
Tritt in Kontakt mit uns unter <a href="mailto:support@kitpvp.world"><code>support@kitpvp.world</code></a>
Oder auf unserem Discord: <a href="https://dc.kitpvp.world"><code>dc.kitpvp.world</code></a>
"""

[store.dialog.paymentMethods]
title="Payment Methods"
description="""
We support <strong>PayPal, credit/debit cards, and 150+ other payment methods</strong> through our secure encrypted gateway Tebex Checkout.

<i>Please note that <bold>Paysafecard</bold> is not currently supported.</i>
"""

[store.dialog.refundPolicy]
title="Refund Policy"
description="""
All sales are final.

<ul>
    <li>We do offer a refund on any item within 14 days after the purchase and without the activation by connecting to our Minecraft: Java Edition server. If you have any issues with any KitPvP World Product, please contact our Support Team.</li>

    <li>If you are banned from the KitPvP World server for breaking our rules, you will lose <strong>access</strong> to your items for the duration of the ban, and will not be eligible for a refund either.</li>
</ul>

<strong>Please read our terms of service before purchasing.</strong>
"""

[store.dialog.login]
title="Please enter your username"
username.title="What is my username?"
username.description="""
If you don’t know what your username is, then please refer to your Minecraft launcher towards the right of the play button.
"""

[store.footer]
purchaseNote = """
All purchases made here are for the KitPvP.World public Minecraft: Java Edition server on the IP “kitpvp.world”. All transactions are secured by Tebex.
"""

[store.footer.tebex]
description="Our checkout process is owned & operated by Tebex Limited, who handle product fulfilment, billing support and refunds."
impressum="Impressum"
tos="Terms & Conditions"
privacy_policy="Privacy Policy"
