[commands.kit]
info = "Dein ausgewähltes Kit ist: <pri><kit_id>"
save.confirm = "Dein Inventar wird somit gespeichert! <bold>Vorhande Inventarsortierungen werden dadurch verloren gehen!/<bold><br>[<bold><confirm></bold>]"
save = "Das Kit Inventar wurde gespeichert."

unselected = "Du hast kein Kit ausgewählt. <click:suggest_command:'/kit select '>/kit select <tag>"

rename = "<bold><pri>UMBENANNT!<reset> Den Anzeigenamen deines <pri>ausgewählten Kits</pri> (<kit_id>) zu <sec><name><reset>"
icon = "<bold><pri>GUTE WAHL!<reset> Das Icon des <pri>ausgewählten Kits</pri> wurde zu <sec><icon><reset> geändert."
icon.empty = "Das Kit Icon kann nicht Luft sein."
give = "Das Inventar wurde geladen."
create = "<bold><sec>ERSTELLT!<reset> Das Kit wurde erstellt und ausgewählt (<pri><id><reset>)"
select = "<bold><#d49de0>AUSGEWÄHLT!<reset> <pri><name><reset>"
reset.error = "Ein Fehler ist aufgetreten, Kit konnte nicht zurückgesetzt werden."
reset = "<bold><#ff0000>ZURÜCKGESETZT!<reset>"
list = "Global Kits: %s"

global.already = "Dieses Kit ist schon global."
global.exists = "Ein Global Kit mit dem Namen <pri><name> <reset>existiert schon."
global.set = "Das Kit wurde globalisiert."
global.unknown = "Ein Global Kit mit dem Namen <pri><name> <reset>existiert nicht."
global.unset = "Das Kit ist nicht mehr global und nun in deinem Besitz (<pri><reset>.)"

current = "Ausgewähltes Kit:<pri> <id>"

[commands.arena]
activate = "Arena wurde aktiviert."
disable = "Arena wurde deaktivert."

cancel.no = "Du hast die Arena-Erstellung noch nicht gestartet. Starten: /arena create <name>;"
cancel = "Arena Erstellung abgebrochen."

create.no = "Du hast die Arena-Erstellung schon gestartet. Abbrechen: /arena create cancel"
create.doSelect = "Du musst eine Region auswählen mit WorldEdit und dich in die Mitte der Arena stellen."
create.alreadyExists = "An arena with the same name already exists. Would you like to teleport to it? <pri><bold><click:run_command:'%s'>Yes"

