untranslated = "<text>"

# Languages
language.change = """
  Deine Sprache ist nun <pri>Deutsch (Deutschland)<reset>.
  <br>Hilf mit, das Netzwerk in deine Sprache zu übersetzen auf <click:open_url:'https://dc.kitpvp.world'><color:#5865f2>unserem Discord</color></click>."
"""

[gui.languages]
title = "Sprache ändern"
untranslated.name = "<gray>Sprache nicht gefunden?"
untranslated.lore = """
  <green>Hilf mit<gray>, das Netzwerk
  <br><gray>in deine Sprache zu übersetzen.
"""
untranslated.book = "<br><br><br><br><br><br><br><br><br><br><br><br><green><bold><click:open_url:'https://dc.kitpvp.world'>Hilf mit!<reset>"

# Generic Things
[generic]
error.clickitem = "Während du dieses Item geklickt hast, ist ein Fehler aufgetreten. Versuche es erneut oder kontaktiere den Support."
error = "Ein Fehler ist aufgetreten."
error.target.offline = "Dieser Spieler ist nicht online."
error.target.unknown = "Dieser Spieler ist uns nicht bekannt."
error.rank.unknown = "Dieser Rang existiert nicht."
error.kit.unknown = "Kit wurde nicht gefunden."

# Chat
[chat]
message.tooSimilar = "Diese Nachricht ähnelt sich zu sehr deiner letzten."

# Games
[games.phase.counter]
starting.secondsFormat = "Das Spiel startet in <pri><seconds_left>s<reset>."
stopping.secondsFormat = "Das Spiel stoppt in <pri><seconds_left>s<reset>."

# Commands

[commands]
coins.self.singular = "Du hast gerade <gold>ein Coin<reset>."
coins.self.plural = "Du hast gerade <gold><coins> Coins<reset>."

coins.other.singular = "<pri><target><reset> hat gerade <gold>ein Coin."
coins.other.plural = "<pri><target><reset> hat gerade <gold><coins> Coins."

xp = """
  <br><yellow>Level Statistiken von <gold><bold><name><reset>
  <br>Platzierung: <rank><reset>
  <br>Level: <level><reset>
  <br>Gesammelte Erfahrung: <xp><reset><yellow><xp_needed><reset>
  <br><dark_gray>| » <xp_bar><reset>
  <br>Gesammelte Achievements: <pri><achievements><reset>/<sec><total_achievements><reset>
"""

ping.self = "Dein Ping ist: <pri><ping>"
ping.other = "Der Ping von <sec><target><reset> ist: <pri><ping>"

language.unknown = "Sprache nicht gefunden. <pri>Bewerbe dich<reset> als Übersetztr auf <click:open_url'https://dc.kitpvp.world'><color:#5865f2>unserem Discord</color></click>unserem Discord</color></click>."

[commands.ranks]
set = "Changed the rank of <pri><target><reset> to <sec><rank><reset."
reload = "<green>Reloaded."

[commands.test]
coins.set = "Deine Coins wurden auf <gold><coins><reset> gesetzt."
coins.remove = "Du hast nun <gold><coins><reset> Coins."
coins.remove.missing = "Dir fehlen <gold><coins><reset> Coins."
coins = "Du hast <gold><coins>"

xp.add = "Deine XP wurden um <pri><xp><reset> XP erhöht."
xp.set = "Deine XP wurden auf <pri><xp>reset> gesetzt."
xp.reset = "Deine XP wurden zurückgesetzt."
xp = "Du hast <pri><xp><reset> XP."

nick.nick = "Du bist nun genickt als <pri><name><reset>."
nick.nicked = "Du bist schon genickt."
nick.unnick = "Du wurdest entnickt."
nick.unnicked = "Du bist nicht genickt."

uuid = "Deine UUID ist: <hover:show_text:'Rechtsklick zum kopieren'><click:copy_to_clipboard:%1$s>%1$s</click></hover>"

[commands.help]
header = "<pri>Informationen zu allen Commands:"

[commands.help.command]
leave = "<yellow>/l <dark_gray>-<reset> Verlässt die Runde, welche du gerade spielst"
coins = "<yellow><click:suggest_command:'/coins '>/coins</click> <dark_gray>-</dark_gray> <reset>Zeigt deine Coins"
friends = "<yellow><click:suggest_command:'/friends'>/friends</click> <dark_gray>-<reset> Öffnet das Freundemenü"
friend_add = "<yellow><click:suggest_command:'/friend add '>/friend add</click> <dark_gray>-<reset> Öffnet das Freundemenü"
clans = "<yellow><click:suggest_command:'/clan'>/clan</click> <dark_gray>-<reset> Öffnet das Clanmenü"
report = "<yellow><click:suggest_command:'/report '>/report</click> <dark_gray>-<reset> Meldet ein Spieler bei dem Serverteam"
bug = "<yellow><click:suggest_command:'/bug '>/bug</click> <dark_gray>-<reset> Meldet ein Bug bei dem Serverteam"
profile = "<yellow><click:suggest_command:'/profile '>/profile</click> <dark_gray>-<reset> Zeigt die Ranked Stats von dem Spieler"
stats = "<yellow><click:suggest_command:'/stats '>/stats</click> <dark_gray>-<reset> Zeigt die allgemeinen Stats von dem Spieler"
