untranslated = "<text>"

# Languages
language.change = """
  Deine Sprache ist nun <pri>Deutsch (Deutschland)<reset>.
  <br>Hilf mit, das Netzwerk in deine Sprache zu übersetzen auf <click:open_url:'https://dc.kitpvp.world'><color:#5865f2>unserem Discord</color></click>.
"""

[core.event.rank.update]
rankedUnblock = """
    Die Sperre in der Ranked Queue wurde für dich aufgehoben.
"""
utility = """
    Du hast einen besonderen Rang erhalten: <pri><rank><reset>
    <br><sec>Vielen Dank</sec> für deine Unterstützung.
"""
team = """
    Du hast einen Team-Rang erhalten: <pri><rank><reset>
    <br><sec>Vielen Dank</sec> für deine Unterstützung.
"""
sponsor = """
    Danke für deinen Kauf auf <pri>kitpvp.world</pri>.
    Du hast den <sec><rank><reset> Rang erhalten.
 """

[gui.languages]
title = "Sprache ändern"
untranslated.name = "<gray>Sprache nicht gefunden?"
untranslated.lore = """
  <green>Hilf mit<gray>, das Netzwerk
  <br><gray>in deine Sprache zu übersetzen.
"""
untranslated.book = """
    <black><bold>Vielen Dank</bold>, dass versuchst KitPvP.world zu verbessern!
    <br>Für das Übersetzen von KitPvP.world in mehr Sprachen, wirst du <bold>einzigartige Belohnungen</bold> erhalten. Bitte
    <bold> öffne ein Ticket</bold> dazu auf unseren Discord:
    <br><click:open_url:'https://dc.kitpvp.world'>                            <br>
    <dark_gray>[<color:#5865f2><bold>Discord beitreten</bold></color>]                                         <br>
"""

[gui.kitView]
title = "Kit Übersicht"

# Generic Things
[generic]
back = "Zurück"
error.clickitem = "Während du dieses Item geklickt hast, ist ein Fehler aufgetreten. Versuche es erneut oder kontaktiere den Support."
error = "Ein Fehler ist aufgetreten."
error.target.offline = "Dieser Spieler ist nicht online."
error.target.unknown = "Dieser Spieler ist uns nicht bekannt."
error.rank.unknown = "Dieser Rang existiert nicht."
error.kit.unknown = "Kit wurde nicht gefunden."

next = "Seite vor"
previous = "Seite zurück"

[time]
seconds = "%s Sekunden"
minutes = "%s Minuten"
hours = "%s Stunden"
days = "%s Tage"
months = "%s Monate"

[time.relative]
seconds = "Vor %s s"
minutes = "Vor %s min"
hours = "Vor %s h"
days = "Vor %s d"
months = "Vor %s m"


# Profile

# Chat
[chat]
message.tooSimilar = "Diese Nachricht ähnelt sich zu sehr deiner letzten."
message.spam = "Du schickst Nachrichten zu schnell ab."

# Games
[games.phase.counter]
starting.secondsFormat = "Das Spiel startet in <pri><seconds_left>s<reset>."
stopping.secondsFormat = "Das Spiel stoppt in <pri><seconds_left>s<reset>."

# Commands

[commands]
coins.self.singular = "Du hast gerade <gold>ein Coin<reset>."
coins.self.plural = "Du hast gerade <gold><coins> Coins<reset>."

coins.other.singular = "<pri><target><reset> hat gerade <gold>ein Coin."
coins.other.plural = "<pri><target><reset> hat gerade <gold><coins> Coins."

xp = """
  <br><yellow>Level Statistiken von <gold><bold><name><reset>
  <br>Platzierung: <rank><reset>
  <br>Level: <level><reset>
  <br>Gesammelte Erfahrung: <xp><reset>/<yellow><xp_needed><reset>
  <br><dark_gray>| » <xp_bar><reset>
  <br>Gesammelte Achievements: <pri><achievements><reset>/<sec><total_achievements><reset>
"""

ping.self = "Dein Ping ist: <pri><ping>"
ping.other = "Der Ping von <sec><target><reset> ist: <pri><ping>"

language.unknown = "Sprache nicht gefunden. <pri>Bewerbe dich<reset> als Übersetztr auf <click:open_url'https://dc.kitpvp.world'><color:#5865f2>unserem Discord</color></click>unserem Discord</color></click>."

rank.singular = "Dein Rang <rank><reset> ist noch für 1 Tag aktiv."
rank.plural = "Dein Rang <rank><reset> ist noch für <days> Tage aktiv."
rank.infinite = "Dein Rang <rank><reset> ist unbegrenzt aktiv."
rank.none = "Du besitzt keinen Rang."

stats = """
    <br><yellow>Duel Statistiken von <gold><bold><rank><reset> <name> <yellow>(<range>)<reset>
    <br><hover:show_text:'Klicke um das Profil zu betrachten'><click:run_command:'/profile %1$s'>[<gold><bold>Profil betrachten</bold></gold>]<reset>
    <br>Globaler Rang: <global_rank><reset>
    <br>Globale Elo: <global_elo><reset>
    <br><style_kills_deaths>K/D: <gray><kills_deaths><reset>
    <br>Spiele gespielt: <gray><games_played><reset>
    <br>Höchste Siegesserie: <top_winstreak><reset>
    <br><hover:show_text:'Klicke für mehr Informationen'><click:run_command:'/level %1$s'>Level: <level> <reset>
"""
stats.currentSeason = "Seasonal"
stats.alltime = "Alltime"

[commands.ranks]
set = "Changed the rank of <pri><target><reset> to <sec><rank><reset."
reload = "<green>Reloaded."

[commands.test]
coins.set = "Deine Coins wurden auf <gold><coins><reset> gesetzt."
coins.remove = "Du hast nun <gold><coins><reset> Coins."
coins.remove.missing = "Dir fehlen <gold><coins><reset> Coins."
coins = "Du hast <gold><coins>"

xp.add = "Deine XP wurden um <pri><xp><reset> XP erhöht."
xp.set = "Deine XP wurden auf <pri><xp>reset> gesetzt."
xp.reset = "Deine XP wurden zurückgesetzt."
xp = "Du hast <pri><xp><reset> XP."

nick.nick = "Du bist nun genickt als <pri><name><reset>."
nick.nicked = "Du bist schon genickt."
nick.unnick = "Du wurdest entnickt."
nick.unnicked = "Du bist nicht genickt."

uuid = "Deine UUID ist: <hover:show_text:'Rechtsklick zum kopieren'><click:copy_to_clipboard:%1$s>%1$s</click></hover>"

[commands]
help = """
    <gold>Informationen zu Commands
    <br>
    <br><click:suggest_command:'/l '><yellow>/l</click> <dark_gray>-<reset> Bringt dich zurück in die Lobby
    <br><click:suggest_command:'/hub '><yellow>/hub</click> <dark_gray>-<reset> Bringt dich zurück in die Lobby
    <br><click:suggest_command:'/duel '><yellow>/duel</yellow> [<yellow>name</yellow>]</click> <dark_gray>- <reset>Fordert den Spieler heraus
    <br><click:suggest_command:'/profile '><yellow>/profile</click> <dark_gray>- <reset>Zeigt die Ranked Stats in jedem Kit an
    <br><click:suggest_command:'/stats '><yellow>/stats</click> <dark_gray>- <reset>Zeigt einen Überblick über deine Stats
    <br><click:suggest_command:'/coins '><yellow>/coins</click> <dark_gray>-</dark_gray> <reset>Zeigt deine Coins</gray>
    <br><click:suggest_command:'/friends'><yellow>/friends</click> <dark_gray>- <reset>Öffnet das Freundemenü
    <br><click:suggest_command:'/friend add '>/<yellow>friend add</click> <dark_gray>- <reset>Fügt ein Spieler als Freund hinzu
"""

# Moderation Stuff

[moderation]
warn = "<pri><target><reset> wurde für <sec><reason><reset> gewarnt und ist nun <red><days_banned><reset> Tage gebannt."
warned.chat = "Du wurdest für <pri><reason><reset> gewarnt und hast nun folgende Strafen erhalten: <br><punishments>"
warned.title.chat = "Chat Bann"
warned.title.kiting = "Achtung Kiting"
report = "Du hast den Spieler <pri><target><reset> für <sec><reason> gemeldet."
report.admin = """
<pri><reported></pri> wurde von <sec><executor></sec> gemeldet:<br>
<reason> <dark_gray>- <description><br>
<br>
<dark_gray>[<bold><yellow>Report Bearbeiten</bold></yellow>] [<bold><green>Profil</bold></green>] [<bold><red>Alts</bold></red>]

"""
error.chat.mute = "Du wurdest für <red><duration><reset> wegen Fehlverhalten aus dem Chat gesperrt: <br><reason>"
error.chat.block = "Ich weiß du bist sauer, aber bitte bleib <bold>respektvoll</bold>."

[moderation.report.reason]
cheating = "Cheating"
chat = "Chat Nachricht(en)"
kiting = "Kiting"
skin = "Skin"
name = "Benutzername"
clan = "Clan-Name"
status = "Freundesstatus"
hunting = "Hunting"
teaming = "Teaming"
boosting = "Boosting"
trolling = "Trolling"

[moderation.admin]
profile.loading = "Lade Profil von <target><reset>..."
profile = """
  Moderationsprofil von <pri><target><reset> (<rank><reset>)<br>
  Benutzer Id: <user_id><br>
  <br>
  Status: <status><reset><br>
  Zuletzt Online: <last_online><reset><br>
  Dauer der Session: <session_time><reset><br>
  <br>
  Client Brand: <brand><reset><br>
  IP: <ip><reset><br>
  ISP (Host Name): <host_name><reset><br>
  <br>
  NameMC Profil: <namemc><reset><br>
  Crafty Profil: <crafty><reset><br>
  Laby Profil: <laby><reset><br>
  Direkt Verdächtige Alts: <hover:show_text:'<yellow>Baum Anzeigen'><alts><reset><br>
  <br>
  Profil-Ladezeit: <loading_time>ms<reset>
"""

alts = """
  Verdächtige Accounts von <pri><target><reset> (<rank><reset>)<br>
  <br>
  <alts><br>
  <own_profile><reset> (Eigenes Profil)
  <br>
  Alts-Ladezeit: <loading_time>ms<reset>
"""

[gui]

[tablist]
header = "<aqua>Du spielst auf <yellow><bold>KITPVP.WORLD"
footer = "<green>ᴜɴᴛᴇʀѕᴛüᴛᴢᴇ ᴜɴѕ ᴀᴜꜰ <red><bold>STORE.KITPVP.WORLD"
