[gui.cosmetics]
armor.equip.all = "<red>Alles anziehen"
armor.unequip.all = "<red>Alles ausziehen"
armor.overview = "Rüstungsset Übersicht"

cosmetics.remove = "Cosmetic ausziehen"

[cosmetics.category]
hats="<aqua>Köpfe"
pets="<blue>Haustiere"
ranks = "<gold>Rang-Cosmetics"
particles="<gold>Partikelübersicht"
trail_particles="Spuren"
join_particles="Join Partikel"
kill_particles="Kill Partikel"
mystic_particles="Mysteriöse Partikel"
gadgets="<dark_green>Gadgets"
armor="<yellow>Kleiderschrank"
effects="<white>Effekte"
abilitities="<green>Fähigkeiten"
balloons="<light_purple>Balloons"

[cosmetics.rarity]
common = "Üblich"
rare = "Selten"
epic = "Episch"
legendary = "Legendär"
rank = "Rang"

[cosmetics.hats]
astronaut="Astronauten Kopf"
feather="Feather Kopf"
champ="Champ Kopf"
grand_champ="Grand Champ Kopf"
ultra="Ultra Kopf"

[cosmetics.trail_particles]
hearts="Herzen Spur"
cherry_blossom="Cherry Blossom Spur"
champ="Champ Spur"
grand_champ="Grand Champ Spur"
ultra="Ultra Spur"

[cosmetics.armor]
leather = "Leder Rüstungsset"
chain = "Ketten Rüstungsset"
gold = "Gold Rüstungsset"
iron = "Eisen Rüstungsset"
diamond = "Diamant Rüstungsset"
netherite = "Netherite Rüstungsset"
champ = "Champ Rüstungsset"
grand_champ = "Grand Champ Rüstungsset"
ultra = "Ultra Rüstungsset"

[cosmetics.pet]
wolf = "Hund"
cat = "Katze"
rabbit = "Hase"
sheep = "Schaf"
cow = "Kuh"
chicken = "Huhn"
slime = "Schleim"
pig = "Schwein"
turtle = "Turtle"
silverfish = "Silberfisch"

[gui.boosters]
use = "<type><reset> benutzt, du wirst nun <multiplier><reset> mehr <unit_type> für <duration><reset> bekommen."
use.active = "Du hast bereits einen <type><reset> aktiv."
use.fail = "Benutzung des Boosters ist fehlgeschlagen. Wurde dieser Booster bereits benutzt?"