[commands.cosmetics]
gift.unknown = "Unable to gift unknown cosmetic: <cosmetic>"
gift = "Gifted <pri><target><reset> the cosmetic <sec><cosmetic>"

[commands.boosters]
query.xp = "<#00FF7F>XP Booster"
query.coins = "<gold>Coin Booster"
query = """
<reset>Zeige deine <bold><query_title></bold> Informationen<br>
<reset>Verfügbare Booster:<br>
<available_boosters><br>
<br>
<reset>Aktivierte Booster:<br>
<active_boosters><br>
<br>
<#00FA9A><reset><bold>»</bold> <sec>+<total_boost>%%</sec> beim Verdienen
"""
query.noActive = "Keine Booster aktiv."
query.noAvailable = "<click:open_url:'https://store.kitpvp.world'><br>Du besitzt keine Booster.<br>Besuche <pri><bold>store.kitpvp.world</bold></pri>,<br>um mehr Booster zu kaufen.</click>"
use.unavailable = "Es sind keine Booster mehr verfügbar."
use.confirm = "<click:run_command:'%s'>Bitte bestätige, dass du den Booster <booster> aktivieren möchtest [<sec><bold>AKTIVIEREN</sec>]</click>"

[gui.cosmetics]
title = "Cosmetics"
armor.equip.all = "<red>Alles anziehen"
armor.unequip.all = "<red>Alles ausziehen"
armor.overview = "Rüstungsset Übersicht"

remove = "Cosmetic ausziehen"

purchase_lore = """
<gray>Kaufbar im <gold>Cosmetics Shop</gold><br>
<gray>Preis<dark_gray>: <gold><price><gray>
"""
unlocked_with_rank = """
<gray>Freigeschaltet mit dem <rank_color><rank> Rang</rank_color><br>
<gray>erhaltbar auf <gold>store.kitpvp.world<gray>.
"""
upgradable_armor = """
<gray>Kaufbar im <gold>Cosmetics Shop</gold><br>
<gray>Durch Aufwerten der Rüstung<gray>
"""

[gui.cosmetics.armorUpgrade]
title = "Armor Aufwerten"
upgradeTo = "<gold>Aufwerten auf <level>"
upgradeTo.lore = """
<gray>Price<dark_gray>: <gold><price>
"""
fully = "<sec>Fully Upgraded!"

level.chain = "Kette"
level.gold = "Gold"
level.iron = "Eisen"
level.diamond = "Diamant"
level.netherite = "Netherite"


[cosmetics.category]
ranks = "<red>Rang Cosmetics"
hats="<aqua>Köpfe"
pets="<blue>Haustiere"
mounts="<yellow>Mounts"
particles="<gold>Partikelübersicht"
trail_particles="<gold>Spuren"
join_particles="<gold>Join Partikel"
kill_particles="<gold>Kill Partikel"
mystic_particles="<light_purple>Mysteriöse Partikel"
gadgets="<dark_green>Gadgets"
armor="<yellow>Kleiderschrank"
effects="<color:#ffd8ad>Effekte"
abilities="<green>Fähigkeiten"
balloons="<light_purple>Balloons"

[cosmetics.rarity]
common = "Üblich"
rare = "Selten"
epic = "Episch"
legendary = "Legendär"
rank_champ = "Champ Rang"
rank_grand_champ = "Grand Champ Rang"
rank_ultra = "Ultra Rang"

[cosmetics.hats]
astronaut="Astronaut Hat"
astronaut.lore="""
    <color:#00FF7F>Kostenlos<br>
    <gray>auf <gold>store.kitpvp.world<gray>.
"""
feather="Feather Hat"
feather.lore="""
    <color:#00FF7F>Kostenlos<br>
    <gray>auf <gold>store.kitpvp.world<gray>.
"""

[cosmetics.pets]
blaze = "Blaze"
fox = "Weißer Fox"
wolf = "Hund"
cat = "Katze"
rabbit = "Hase"
panda="Baby Panda"
sheep = "Schaf"
cow = "Kuh"
chicken = "Huhn"
slime = "Schleim"
pig = "Schwein"
turtle = "Turtle"
silverfish = "Silberfisch"

[cosmetics.mounts]
flying_squid="Flug-Tintenfisch"
teleporting_enderman="Teleport-Enderman"
climbing_cave_spider="Kletterspinne"
iron_golem="Eisengolem"
panda="Panda"
horse="Pferd"
magma_cube="Magma Cube"

[cosmetics.trail_particles]
ultra="<red>Ultra Spur"
grand_champ="<aqua>Grand Champ Spur"
champ="<gold>Champ Spur"
hearts="Herzen Spur"
cherry_blossom="Kirschblüten Spur"
cherry_blossom.lore="""
    <color:#00FF7F>Mit Dabei<br>
    <gray>auf <gold>store.kitpvp.world<gray>.
"""

[cosmetics.join_particles]
ultra="<red>Ultra Join Partikel"
grand_champ="<aqua>Grand Champ Join Partikel"
champ="<gold>Champ Join Partikel"

[cosmetics.kill_particles]

[cosmetics.gadgets]
grappling_hook = "Enterhaken"

[cosmetics.armor]
ultra = "<red>Ultra Rüstungsset"
grand_champ = "<aqua>Grand Champ Rüstungsset"
champ = "<gold>Champ Rüstungsset"
netherite = "Netherite Rüstungsset"
diamond = "Diamant Rüstungsset"
iron = "Eisen Rüstungsset"
gold = "Gold Rüstungsset"
chain = "Ketten Rüstungsset"

piece.helmet = "Helm"
piece.chestplate = "Brustplatte"
piece.leggings = "Hose"
piece.boots = "Schuhe"

[cosmetics.effects]
speed="Speed"
jump_boost="Sprungkraft"
slow_falling="Langsamer Fall"

[cosmetics.abilities]
double_jump="Doppelsprung"
flight = "Fliegen"

[cosmetics.balloons]
ultra = "<red>Ultra Ballon"
grand_champ="<aqua>Grand Champ Ballon"
champ="<gold>Champ Ballon"
orange="Orange Ballon"
red="Red Ballon"
purple="Purple Ballon"
pink="Pink Ballon"
light_pink="Light Pink Ballon"
white="White Ballon"
light_gray="Light Gray Ballon"
yellow="Yellow Ballon"
lime="Lime Ballon"
green="Green Ballon"
light_blue="Light Blue Ballon"

[gui.boosters]
use = "<type><reset> benutzt, du wirst nun <rarity_color><multiplier>%%<reset> mehr <unit_type> für <duration><reset> bekommen."
use.active = "Du hast bereits einen <type><reset> aktiv."
use.fail = "Benutzung des Boosters ist fehlgeschlagen. Wurde dieser Booster bereits benutzt?"
item.lore = """
    <gray>Seltenheit</gray><dark_gray>:</dark_gray> <rarity><reset><br>
    <gray>Multiplikator</gray><dark_gray>:</dark_gray> <rarity_color><multiplier></rarity_color><br>
    <gray>Dauer</gray><dark_gray>:</dark_gray> <rarity_color><duration></rarity_color>
"""
