friend.accept = "Akzeptieren"
friend.accept.error = "Die Freundschaftsanfrage konnte nicht akzeptiert werden"
friend.decline = "Ablehnen"
friend.lastOnline = "Zuletzt Online: "
friend.sent = "Gesendet: "
friend.request = """
Du hast eine Freundschaftsanfrage von dem Spieler <target><reset> erhalten:<br>
<green><click:run_command:'%s'>[<bold>Annehmen</bold>]</click></green>
<red> <click:run_command:'%s'>[<bold>Ablehnen</bold>]</click></red>
"""

friend.join = "<sec><bold>●<reset> Dein Freund <friend><reset> ist nun <sec>online<reset>."
friend.leave = "<red><bold>●<reset> Dein Freund <friend><reset> ist nun <red>offline<reset>."

[gui.friend]
settings.clan.title = "Claneinstellungen"
settings.requests.title = "Anfrageeinstellungen"

main.title = "Freunde"
party.title = "Partys"
changeStatus.title = "Freundestatus ändern"
requests.title = "Freundschaftsanfragen"
settings.title = "Einstellungen"
settings.request.title = "Anfrageeinstellungen"
settings.clanRequests.title = "Clananfrageeinstellungen"

target.inviteClan = "Zum Clan einladen"
target.favourite.add = "Als Favorite hinzufügen"
target.favourite.remove = "Als Favorite entfernen"
target.inviteParty = "In Party einladen"
target.jump = "Nachspringen"
target.remove = "Freund entfernen"

[gui.friend.settings.friendRequests]
title = "Freundschaftsanfrageeinstellungen"
default = "<gray>Spieler"
default.lore = "<gray>Jeder darf dir Freundschaftsanfragen senden"
premium = "<gold>Premium"
premium.lore = "<gray>Premiums dürfen dir Freundschaftsanfragen senden"
youtube = "<dark_red>YT"
youtube.lore = "<gray>YouTuber dürfen dir Freundschaftsanfragen senden"
vip = "<dark_red>VIP"
vip.lore = "<gray>Streamer dürfen dir Freundschaftsanfragen senden"
team = "<red>Team"
team.lore = "<gray>Unser Team darf dir Freundschaftsanfragen senden"
party = "<light_purple>Party"
party.lore = "<gray>Party-Mitglieder dürfen dir Freundschaftsanfragen senden"
clan = "<yellow>Clan"
clan.lore = "<gray>Clan-Mitglieder dürfen dir Freundschaftsanfragen senden"

[gui.friend.settings.friend]
title = "Freundeseinstellungen"
allowPrivateMessages = "Erlaube Privatnachrichten"
allowPrivateMessages.lore = "Deine Freunde können dir eine Nachricht per MSG senden"
allowOfflinePrivateMessages = "Erlaube Offline-Nachrichten"
allowOfflinePrivateMessages.lore = "Freunde können dir Nachrichten senden, obwohl du offline bist"
announceFriendOnlineStatus = "Online -und Offlinenachrichten anzeigen"
announceFriendOnlineStatus.lore = "Bekomme eine Chatnachricht, wenn dein Freund den Server betritt/verlässt"
allowSpectate = "Zuschauen erlauben"
allowSpectate.lore = "Erlaube deinen Freunden deine Spiele zu beobachten"
showOnlineStatus = "Onlinestatus anzeigen"
showOnlineStatus.lore = "Erlaube deinen Freunden zu sehen ob du Online bist"

[commands.friend]
error.notFriend = "Dieser Spieler ist nicht dein Freund."

add = "Du hast eine Freundschaftsanfrage an <target><reset> gesendet."
add.friend = "Dieser Spieler ist schon dein Freund."
add.off = "Dieser Spieler akzeptiert deine Anfrage nicht."
accept = "Du hast die Freundschaftsanfrage von <target><reset> angenommen."
accept.noRequest = "Du hast keine Freundschaftsanfrage von diesem Spieler bekommen."

decline = "Du hast die Freundschaftsanfrage von <target><reset> abgelehnt."
decline.all = "Du hast <pri><requests> Freundschaftsanfragen<reset> abgelehnt."

remove = "Dieser Spieler ist nun nicht mehr dein Freund."
remove.error = "Beim Entfernen ist ein Fehler aufgetreten. War dieser Spieler überhaupt dein Freund?"

favourite.add = "<target><reset> wurde zu deinen Favoriten hinzugefügt."
favourite.add.error = "Das Hinzufügen des Favoriten ist fehlgeschlagen."
favourite.remove = "<target><reset> wurde aus deinen Favoriten entfernt."
favourite.remove.error = "Das Entfernen des Favoriten ist fehlschlagen."

list = """Deine Freundesliste (Seite <page><reset>):<br>
<list>
"""

clear = "Du hast <pri><friends> Freunde<reset> entfernt."
clear.all.confirm = "Bist du dir sicher, dass du <bold>alle deine Freunde</bold> (<bold>einschließlich Favoriten</bold>) löschen willst? Diesen Vorgang kannst du nicht wieder rückgängig machen! <br><confirm>"
clear.confirm = "Bist du dir sicher, dass du <bold>alle deine Freunde</bold> außer Favoriten löschen willst? Diesen Vorgang kannst du nicht wieder rückgängig machen! <br><confirm>"

cancel = "Die Freundschaftsanfrage zu <target><reset> wurde zurückgezogen."
cancel.noRequest = "Du hast dem Spieler <target><reset> keine Freundschaftsanfrage gesendet."
cancel.all = "Du hast <pri><requests> Freundschaftsanfragen<reset> abgebrochen."

request = """Freundschaftsanfragen (Seite <page><reset>): <br>
<list>
"""
