[error]
notEnoughPlayers = "Nicht genügend Spieler online."
border = "Außerhalb der Border"
noGame = "<red>Es wurde kein Spiel gefunden"

[phases]
start = "<green>Lasst den Kampf beginnen."
border = "Die Border beginnt sich zu verkleinern. Der Kampf endet in <minutes_left> Minuten."
stop = "<red>Spiel zu Ende"

[event]
player.leave = "<pri><name><reset> hat das Duel verlassen."
player.join = "<pri><name><reset> hat das Spiel betreten."
player.spectate = "<pri><name> <reset>schaut zu."
win = """
<team>
<br><yellow>hat gewonnen!
"""
win.firstTo = """
<gray>Runde <round><reset>
<br><aqua><self_points><dark_gray> - <red><opponent_points>
"""
win.firstTo.end = """
<team><reset><yellow> hat gewonnen
<br><aqua><self_points><dark_gray> - <red><opponent_points>
"""

[win]
stats = """
  <br>Schaden erlitten: <aqua><damage_taken_self></aqua>/<red><damage_taken_opponent></red>
  <br>Herzen verbleibend: <aqua><health_self>❤</aqua>/<red><health_opponent>❤</red>
  <br>Schläge erlitten: <aqua><hits_taken_self></aqua>/<red><hits_taken_opponent></red>
  <br>Davon Crits: <aqua><crits_taken_self></aqua>/<red><crits_taken_opponent></red>
"""

elo = "<winner> <reset><is_solo_game:hat:haben> <red><loser> <reset>in Kit <kit><reset> besiegt."
single = "In einem epischen Kampf um Leben und Tod siegte <pri><name><reset>."

[features]
inventory = "<aqua>Inventar"
teleport = "<yellow>Teleportieren"
leave = "<red>Verlassen"

[commands.game]
error.minimum = "Es müssen zwei Spieler in einem Duel sein."
start = "Starte Spiel <game_id>"

[gui.selectInventory]
title = "Spieler auswählen"

[gui.teleport]
title = "Teleportieren"
