[commands.setup]
property.unknown = "Einstellung konnte nicht gefunden werden."
property.get = "<aqua><property> <reset> == <value>"
property.set = "<pri><property> <reset>= <value>"
property.allset = "Alle Einstellungen = <value>"
property.list.single = "<gray><property><reset> = <hover:show_text:'Zu <notvalue> ändern'><click:run_command:'/setup property %b %b'><value></click></hover>"
property.list = "<green><bold>Properties<reset>:<newline><properties>"

lobby.set = "Lobby-Welt wurde gesetzt."
boundary.set = "Boundary wurde gesetzt."
spawn.set = "Spawnpunkt wurde gesetzt."
upload = "Config wurde erfolgreich hochgeladen: <url>"
upload.failed = "Fehler beim Config hochladen ist aufgetreten: <statusCode>"

help = "<red><bold>SETUP: <reset><newline>1. <click:run_command:'/setup lobby'>Lobby-Welt setzen</click><newline>2. <click:suggest_command:'/setup boundary 30'>Boundary setzen (Minimum Y Höhe)</click><newline>3. <click:run_command:'/setup spawnpoint'>Spawn setzen</click><newline>4. <click:run_command:'/setup queueNPC'>Queue NPC setzen</click><newline>4. <click:run_command:'/setup properties'>Properties bearbeiten</click><newline>5. <click:run_command:'/setup end'>Setup fertigstellen</click>"

[hotbar]
challenge = "<gray>Herausfordern"
clan = "<yellow>Clan"
items = "<gold>Items"
friends = "<green>Freunde"
language = "<red>Sprache"
lobby = "<aqua>Lobby"

nick.nicked = "<gray>Du Bist<dark_gray>: <green>Genickt"
nick.unnicked = "<gray>Du Bist<dark_gray>: <red>Nicht Genickt"
nick.development = "Dieses Feature ist derzeit noch in Entwicklung. Danke TheAntCraft, dass ich diese Nachricht, wegen deines Spammens hinzufügen musste :)"

[kitLayout]
saved = "Die Kitsortierung wurde gespeichert."
error = "Ein Fehler ist passiert. Bitte versuche es erneut und kontaktiere den Support."
reset = "Zurücksetzen"

[gui.lobbySwitcher]
title = "Lobby Switcher"
premium = "Du benötigst mindestens den <gold>Premium Rang</gold> um diesen Server zu betreten."

[leaderboard]
loading = "Das Leaderboard läd derzeit noch! Der Vorgang kann bis zu 3 Sekunden dauern."

[scoreboard]
clan = """
  <br>Clan<gray>:
  <br><gray><clan>
  <br>
  <br>Clan Elo<gray>:
  <br><gray><clanelo>
  <br>
  <br>Clan Level<gray>:
  <br><gray><clanlevel>★
  <br>
  <br>Clan Coins<gray>:
  <br><gold><clancoins>
  <br>
  <br>Clan Spieler<gray>:
  <br><aqua><onlineclanmembers><gray>/<dark_gray><totalclanmembers>
"""

self = """
  <br>Rang<gray>:
  <br><rank>
  <br>
  <br>Elo<gray>:
  <br><gray><elo>
  <br>
  <br>Spielzeit<gray>:
  <br><yellow><hours>h
  <br>
  <br>Coins<gray>:
  <br><gold><coins>
  <br>
  <br>Freunde<gray>:
  <br><green><onlinefriends><gray>/<dark_gray><totalfriends>
"""

selfSecondary = """
  <br>Rang<gray>:
  <br><rank>
  <br>
  <br>Elo<gray>:
  <br><gray><elo>
  <br>
  <br>Level<gray>:
  <br><level>
  <br>
  <br>Coins<gray>:
  <br><gold><coins>
  <br>
  <br>Freunde<gray>:
  <br><green><onlinefriends><gray>/<dark_gray><totalfriends>
"""

[features]
levelup.title = """
  <green>Level Up!
  <br><level> <gray>→ <new_level>
"""
discord = "Join auf <click:open_url:'https://dc.kitpvp.world'><color:#5865f2>unseren Discord</color>: <dark_gray>[<sec>Klick Hier</sec>]</dark_gray></click>"
