[hotbar]
challenge = "<gray>Herausfordern"
party.member = "<purple>Party"
party.moderator = "<purple>Party Moderieren"
party.leader = "<purple>Party Einstellen"
party.none = "<gray>In keiner Party"
items = "<gold>Items"
friends = "<green>Freunde"
kiteditor = "<red>Kit Editor"
lobby = "<aqua>Lobby"

nick.nicked = "<gray>Du Bist<dark_gray>: <green>Genickt"
nick.unnicked = "<gray>Du Bist<dark_gray>: <red>Nicht Genickt"
nick.development = "Dieses Feature ist derzeit noch in Entwicklung."

[gui.kitLayout]
saved = "Die Kitsortierung für <kit><reset> wurde gespeichert."
error = "Ein Fehler ist passiert. Bitte versuche es erneut und kontaktiere den Support."
reset = "Zurücksetzen"
reset.confirm = "<red>Zurücksetzten Bestätigen"
reset.cancel = "Zürücksetzen abbrechen"
select.title = "Kit Sortierung: Kit Auswählen"

[gui.lobbySwitcher]
title = "Lobby Switcher"
champ = "Du benötigst mindestens den <gold>Champ Rang</gold>, um diesen Server zu betreten."
connected = " (Verbunden)"
connectTo.lore = "<gray>Automatisch nach dem Duel mit dieser Lobby verbinden"

[leaderboard]
loading = "Das Leaderboard läd derzeit noch! Der Vorgang kann bis zu 3 Sekunden dauern."

[scoreboard]
clan = """
  <br>Clan<gray>:
  <br><gray><clan>
  <br>
  <br>Clan Elo<gray>:
  <br><gray><clanelo>
  <br>
  <br>Clan Level<gray>:
  <br><gray><clanlevel>★
  <br>
  <br>Clan Coins<gray>:
  <br><gold><clancoins>
  <br>
  <br>Clan Spieler<gray>:
  <br><aqua><onlineclanmembers><gray>/<dark_gray><totalclanmembers>
"""

self = """
  <br>Rang<gray>:
  <br><rank>
  <br>
  <br>Elo<gray>:
  <br><gray><elo>
  <br>
  <br>Spielzeit<gray>:
  <br><yellow><hours>h
  <br>
  <br>Coins<gray>:
  <br><gold><coins>
  <br>
  <br>Freunde<gray>:
  <br><green><onlinefriends><gray>/<dark_gray><totalfriends>
"""

selfSecondary = """
  <br>Rang<gray>:
  <br><rank>
  <br>
  <br>Elo<gray>:
  <br><gray><elo>
  <br>
  <br>Level<gray>:
  <br><level>
  <br>
  <br>Coins<gray>:
  <br><gold><coins>
  <br>
  <br>Freunde<gray>:
  <br><green><onlinefriends><gray>/<dark_gray><totalfriends>
"""

[features]
levelup.title = """
  <green>Level Up!
  <br><level> <gray>→ <new_level>
"""
discord = "Join auf <click:open_url:'https://discord.gg/Pk4CJ6dwHA'><color:#5865f2>unseren Discord</color>: <dark_gray>[<sec>Klick Hier</sec>]</dark_gray></click>"
store = "<click:open_url:'https://store.kitpvp.world'>Hey, falls dir unsere Projekte bisher gefallen und Du uns bei weiteren unterstützen möchtest, überlege dir doch einen Rang auf <gold><bold>store.kitpvp.world</bold></gold> zu kaufen :)"
bots = "PvP Bots werden am 24.12 releasen."
version = "Für die beste Erfahrung, spiel auf der Version <version>"