[store.category]
ranks="Ränge"
xp_booster="XP Booster"
coins_booster="Coins Booster"
more = "Mehr Items"

[store.category.ranks]
champ="Champ"
ultra="Ultra"
grandChamp="Grand Champ"

[store.category.xp_booster]
xpBooster8h4x="XP Booster 400%% - 8 Std."
xpBooster3d4x="XP Booster 400%% - 3 Tage"
xpBooster7d4x="XP Booster 400%% - 7 Tage"

[store.category.coins_booster]
coinsBooster8h4x="Coins Booster 400%% - 8 Std."
coinsBooster3d4x="Coins Booster 400%% - 3 Tage"
coinsBooster7d4x="Coins Booster 400%% - 7 Tage"

[store.category.more]
hatAstronaut="Astronauten Helm"
hatFeather="Feder Hut"
trailCherryBlossom="Cherry Blossom Spur"

[store.actions]
free="Kostenlos"
