# Languages
language.change = "Your language is now English (United States)<newline>Help us translate the network into your language on <click:open_url'https://dc.kitpvp.world'>our Discord</click>."

[gui.languages]
untranslated.name = "Didn't find your language?"
untranslated.lore.1 = "<green>Apply <gray>as a translator,"
untranslated.lore.2 = "to translate your language."
untranslated.book = "<green><bold><click:open_url:'https://dc.kitpvp.world'>Apply here!<reset>"

# Common
[gui.common]
error.clickitem = "An unexpected error occurred trying to click that item"

# Games
[games.phase.counter]
secondsFormat = "The game starts in <pri><secondsLeft>s<reset>"

# Commands
[commands]
coins.self.singular = "You currently have <gold>one Coin<reset>."
coins.self.plural = "You currently have <gold><coins> Coins<reset>."

coins.other.singular = "<pri><target><reset> currently has <gold>one Coin"
coins.other.plural = "<pri><target><reset> currently has <gold><coins> Coins"
