# A prefix used for every plugin
prefix = "<gray>[<yellow>KitPvP.World<gray>] <reset>"

[[languages]] # First: will be the default language
languageCode = "en"
displayName = "English (United States)"
headId = 44718

[[languages]]
languageCode = "de"
displayName = "Deutsch (Deutschland)"
headId = 43579
