name: Build and deploy the language.bundle to the repository

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'

concurrency:
  group: production
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deploy:
    environment: "promoted"
    runs-on: ubuntu-latest
    env:
      repository_username: ${{ secrets.repository_username }}
      repository_password: ${{ secrets.repository_password }}
      repository_url: https://maven.kitpvp.world/public-snapshots/world/kitpvp/translations/
    steps:
      - uses: actions/checkout@v3
      - name: Validate
        run: lib/translation-compiler --publish
