name: Publish the languages to the repository

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      repository_username: ${{ secrets.repository_username }}
      repository_password: ${{ secrets.repository_password }}
      repository_url: ${{ secrets.repository_url }}
    steps:
      - uses: actions/checkout@v3
      - name: Validate
        run: lib/translation-compiler publish
