name: Publish the languages to the repository

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      repository_username: ${{ secrets.repository_username }}
      repository_password: ${{ secrets.repository_password }}
      repository_url: ${{ secrets.repository_url }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate
        run: java -jar lib/translations-validator-master-SNAPSHOT-proguarded.jar debug publish