name: Validate the translation files

on:
  workflow_dispatch:
  push:
  pull_request:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate
        run: lib/translation-compiler
